module Rubex
  class CodeWriter
    attr_reader :code

    def initialize
      @code = <<-CODE
        /* C extension for #{target_name}.
           This file in generated by Rubex. Do not change!
        */
        
      CODE
    end

    def write_func_declaration return_type, c_name
      @code << "#{return_type} #{c_name} "
      @code << "("
      @code << "int argc, VALUE* argv, VALUE #{Rubex::ARGS_PREFIX}self"
      @code << ");"
      new_line
    end

    def write_func_definition_header return_type, c_name
      @code << "#{return_type} #{c_name} "
      @code << "("
      @code << "int argc, VALUE* argv, VALUE #{Rubex::ARGS_PREFIX}self"
      @code << ")"
      @code << "{"
    end

    def << s
      @code << s
    end

    def new_line
      @code << "\n"
    end
  end
end
