#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'

require_relative 'lexer.rex.rb'
require_relative 'ast.rb'

include Rubex::AST

module Rubex
  class Parser < Racc::Parser

module_eval(<<'...end parser.racc/module_eval...', 'parser.racc', 402)

def parse file_name
  @lexer = Rubex::Lexer.new
  @yydebug = true
  @custom_dtypes = {}
  @prev_token = nil
  @lexer.parse_file file_name
end

def next_token
  t = @lexer.next_token

  if !t.nil?
    if t[0] == :tIDENTIFIER
      if @custom_dtypes.has_key?(t[1]) && !(@prev_token[0] == :kSTRUCT)
        t = [:tCUSTOM_DTYPE, t[1]]
      end
      t = check_for_primitive_dtype(t)
      t = check_for_keyword(t)
    end
  end

  @prev_token = t
  t
end

def check_for_keyword token
  match = token[1]
  if match == "def"
    return [:kDEF, match]
  elsif match == "do"
    return [:kDO, match]
  elsif match == "end"
    return [:kEND, match]
  elsif match == "return"
    return [:kRETURN, match]
  elsif match == "print"
    return [:kPRINT , match]
  elsif match == "if"
    return [:kIF    , match]
  elsif match == "elsif"
    return [:kELSIF , match]
  elsif match == "else"
    return [:kELSE  , match]
  elsif match == "then"
    return [:kTHEN  , match]
  end

  return token
end

def check_for_primitive_dtype token
  match = token[1]
  if match == "char"
    return [:kDTYPE_CHAR, match]
  elsif match == "i8"
    return [:kDTYPE_I8, match]
  elsif match == "i16"
    return [:kDTYPE_I16, match]
  elsif match == "i32"
    return [:kDTYPE_I32, match]
  elsif match == "i64"
    return [:kDTYPE_I64, match]
  elsif match == "u8"
    return [:kDTYPE_UI8, match]
  elsif match == "u16"
    return [:kDTYPE_UI16, match]
  elsif match == "u32"
    return [:kDTYPE_UI32, match]
  elsif match == "u64"
    return [:kDTYPE_UI64, match]
  elsif match == "int"
    return [:kDTYPE_INT, match]
  elsif match == "long"
    return [:kDTYPE_LINT, match]
  elsif match == "f32"
    return [:kDTYPE_F32, match]
  elsif match == "float"
    return [:kDTYPE_F32, match]
  elsif match == "f64"
    return [:kDTYPE_F64, match]
  elsif match == "double"
    return [:kDTYPE_F64, match]
  elsif match == "object"
    return[:kDTYPE_ROBJ, match]
  end

  token
end

def binary_op val
  Expression::Binary.new val[0], val[1], val[2]
end

def unary_op val
  Expression::Unary.new val[0], val[1]
end

def op_assign val # expr, op_assign, expr => expr = expr op expr
  Statement::Assign.new(val[0], binary_op([val[0], val[1][0], val[2]]))
end

def node_variable dtype, di
  if di[:name].is_a? Expression::ArrayRef
    var = Statement::CArrayDecl.new(dtype, di[:name], di[:value])
  elsif di[:pointer]
    if di[:pointer] == '*'
      var = Statement::CPtrDecl.new(dtype, di[:name], di[:value])
    end
  else
    var = Statement::VarDecl.new(dtype, di[:name], di[:value])
  end

  var
end

def add_dtype_to_lexer dtype
  @custom_dtypes[dtype] = true
end
...end parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    34,    35,    37,   150,   168,   150,   256,    38,    39,   225,
   226,    52,    53,    54,    41,   165,    29,   165,    57,    58,
    59,    60,    61,    62,    63,    64,    65,    66,    67,    68,
    69,    70,    71,    72,    73,    74,    75,    76,     8,   114,
   119,   152,    46,   152,   115,   120,    26,   115,   213,   236,
   156,   157,   113,   214,   237,     9,    26,     6,   117,     8,
     8,   111,    27,    34,    35,    37,    16,    49,    50,    51,
    38,    39,    27,    18,    52,    53,    54,    41,     6,    29,
    19,    57,    58,    59,    60,    61,    62,    63,    64,    65,
    66,    67,    68,    69,    70,    71,    72,    73,    74,    75,
    76,   114,   202,   115,    13,    46,    13,    14,    22,    14,
    13,   113,    25,    14,   130,   131,   132,   133,   134,   135,
   111,    13,    13,    86,    14,    14,    34,    35,    37,    87,
    49,    50,    51,    38,    39,   158,   159,    52,    53,    54,
    41,    90,    29,   107,    57,    58,    59,    60,    61,    62,
    63,    64,    65,    66,    67,    68,    69,    70,    71,    72,
    73,    74,    75,    76,    13,   187,   108,    14,    46,    57,
    58,    59,    60,    61,    62,    63,    64,    65,    66,    67,
    68,    69,    70,    71,    72,    73,    74,    75,    76,    34,
    35,    37,   110,    49,    50,    51,    38,    39,   225,   226,
    52,    53,    54,    41,   116,    29,   121,    57,    58,    59,
    60,    61,    62,    63,    64,    65,    66,    67,    68,    69,
    70,    71,    72,    73,    74,    75,    76,    13,   124,    13,
    14,    46,    14,   125,   127,   130,   131,   132,   133,   134,
   135,   114,   136,   138,   139,   140,   141,   142,   143,   153,
   161,   162,    34,    35,    37,   137,    49,    50,    51,    38,
    39,   173,   152,    52,    53,    54,    41,   183,    29,   184,
    57,    58,    59,    60,    61,    62,    63,    64,    65,    66,
    67,    68,    69,    70,    71,    72,    73,    74,    75,    76,
   132,   133,   134,   135,    46,    90,   134,   203,   130,   131,
   132,   133,   134,   135,   206,   136,   138,   139,   140,   141,
   142,   143,   207,   211,   212,    34,    35,    37,   137,    49,
    50,    51,    38,    39,   117,   215,    52,    53,    54,    41,
   222,    29,   134,    57,    58,    59,    60,    61,    62,    63,
    64,    65,    66,    67,    68,    69,    70,    71,    72,    73,
    74,    75,    76,   132,   133,   134,   135,    46,    57,    58,
    59,    60,    61,    62,    63,    64,    65,    66,    67,    68,
    69,    70,    71,    72,    73,    74,    75,    76,    34,    35,
    37,   134,    49,    50,    51,    38,    39,   134,   134,    52,
    53,    54,    41,   227,    29,   230,    57,    58,    59,    60,
    61,    62,    63,    64,    65,    66,    67,    68,    69,    70,
    71,    72,    73,    74,    75,    76,   168,    52,    53,    54,
    46,   238,    52,    53,    54,   110,   242,   247,    52,    53,
    54,   130,   131,   132,   133,   134,   135,   261,   115,   156,
   157,   158,   159,   256,    95,    49,    50,    51,    99,    95,
    52,    53,    54,    99,   114,    95,   115,    13,    94,    99,
    14,   nil,    13,    94,   113,    14,   nil,    13,   nil,    94,
    14,    97,   nil,    49,    50,    51,    97,   105,    49,    50,
    51,    99,    97,   nil,    49,    50,    51,    52,    53,    54,
   nil,    94,    52,    53,    54,    52,    53,    54,   130,   131,
   132,   133,   134,   135,   nil,   nil,    49,    50,    51,    13,
   259,   nil,    14,   260,    95,   nil,   nil,    13,    99,    95,
    14,    13,   105,    99,    14,   nil,    99,   nil,    94,    52,
    53,    54,   nil,    94,   nil,   nil,    94,    52,    53,    54,
   nil,    97,   nil,    49,    50,    51,    97,   nil,    49,    50,
    51,    49,    50,    51,   nil,   nil,    95,    52,    53,    54,
    99,   nil,   nil,   nil,    95,    52,    53,    54,    99,   nil,
    94,   130,   131,   132,   133,   134,   135,   nil,    94,   nil,
   nil,   nil,   nil,    97,   105,    49,    50,    51,    99,   nil,
   nil,    97,    95,    49,    50,    51,    99,   nil,    94,    52,
    53,    54,   nil,   nil,   nil,   nil,    94,    52,    53,    54,
   nil,   nil,   nil,    49,    50,    51,   nil,   nil,   nil,    97,
   nil,    49,    50,    51,   nil,   nil,    95,    52,    53,    54,
    99,   nil,   nil,   nil,    95,    52,    53,    54,    99,   nil,
    94,   130,   131,   132,   133,   134,   135,   nil,    94,   nil,
   nil,   nil,   nil,    97,    95,    49,    50,    51,    99,   nil,
   nil,    97,    95,    49,    50,    51,    99,   nil,    94,    52,
    53,    54,    52,    53,    54,   nil,    94,    52,    53,    54,
   nil,    97,   nil,    49,    50,    51,   nil,   nil,   nil,    97,
   nil,    49,    50,    51,   nil,   nil,    95,   nil,   nil,   105,
    99,   nil,   nil,    99,   105,    52,    53,    54,    99,   nil,
    94,   nil,   nil,    94,    52,    53,    54,   nil,    94,   nil,
   nil,   nil,   nil,    97,   nil,    49,    50,    51,    49,    50,
    51,   nil,   105,    49,    50,    51,    99,    52,    53,    54,
   nil,   105,    52,    53,    54,    99,    94,   nil,    52,    53,
    54,   nil,   nil,   nil,   nil,    94,   nil,   nil,   nil,   nil,
   nil,    49,    50,    51,   105,   nil,   nil,   nil,    99,   105,
    49,    50,    51,    99,   nil,   105,   nil,   nil,    94,    99,
    52,    53,    54,    94,   nil,    52,    53,    54,   nil,    94,
   nil,   nil,   nil,    49,    50,    51,   nil,   nil,    49,    50,
    51,   nil,   nil,   nil,    49,    50,    51,   105,    52,    53,
    54,    99,   105,    52,    53,    54,    99,   nil,   nil,   nil,
   nil,    94,   nil,   nil,   nil,   nil,    94,   nil,   nil,   nil,
   nil,    52,    53,    54,   nil,   105,    49,    50,    51,    99,
   105,    49,    50,    51,    99,   nil,   nil,   nil,   nil,    94,
    52,    53,    54,   nil,    94,    52,    53,    54,   105,   nil,
   nil,   nil,    99,   nil,    49,    50,    51,   nil,   nil,    49,
    50,    51,    94,    52,    53,    54,   nil,   105,    52,    53,
    54,    99,   105,   nil,   nil,   nil,    99,    49,    50,    51,
   nil,    94,   nil,   nil,   nil,   nil,    94,    52,    53,    54,
    95,   nil,   234,   nil,    99,    95,    49,    50,    51,    99,
   nil,    49,    50,    51,    94,    52,    53,    54,   nil,    94,
   nil,    52,    53,    54,    95,   nil,   nil,    97,    99,    49,
    50,    51,    97,   nil,    49,    50,    51,   nil,    94,    52,
    53,    54,   105,   nil,   nil,   nil,    99,   nil,   105,   nil,
   nil,    97,    99,    49,    50,    51,    94,    52,    53,    54,
   nil,   nil,    94,   nil,   nil,   nil,    95,   nil,   nil,   nil,
    99,    49,    50,    51,   nil,   nil,   nil,    49,    50,    51,
    94,   nil,   nil,   nil,    95,   nil,   nil,   nil,    99,   nil,
   nil,   nil,   nil,    97,   nil,    49,    50,    51,    94,   nil,
   nil,   122,   130,   131,   132,   133,   134,   135,   nil,   nil,
   nil,    97,   nil,    49,    50,    51,    84,   nil,    29,   nil,
    57,    58,    59,    60,    61,    62,    63,    64,    65,    66,
    67,    68,    69,    70,    71,    72,    73,    74,    75,    76,
    84,   nil,    29,   nil,    57,    58,    59,    60,    61,    62,
    63,    64,    65,    66,    67,    68,    69,    70,    71,    72,
    73,    74,    75,    76,   202,   nil,   nil,   nil,   nil,    13,
   nil,   nil,    14,   nil,   nil,   nil,   130,   131,   132,   133,
   134,   135,   nil,   136,   138,   139,   140,   141,   142,   143,
   130,   131,   132,   133,   134,   135,   137,    57,    58,    59,
    60,    61,    62,    63,    64,    65,    66,    67,    68,    69,
    70,    71,    72,    73,    74,    75,    76,   nil,   nil,   nil,
   nil,   nil,    13,   nil,   nil,    14,    57,    58,    59,    60,
    61,    62,    63,    64,    65,    66,    67,    68,    69,    70,
    71,    72,    73,    74,    75,    76,   nil,   nil,   nil,   nil,
    80,    57,    58,    59,    60,    61,    62,    63,    64,    65,
    66,    67,    68,    69,    70,    71,    72,    73,    74,    75,
    76,   nil,   nil,   nil,   nil,    80,    57,    58,    59,    60,
    61,    62,    63,    64,    65,    66,    67,    68,    69,    70,
    71,    72,    73,    74,    75,    76,    57,    58,    59,    60,
    61,    62,    63,    64,    65,    66,    67,    68,    69,    70,
    71,    72,    73,    74,    75,    76,    57,    58,    59,    60,
    61,    62,    63,    64,    65,    66,    67,    68,    69,    70,
    71,    72,    73,    74,    75,    76,   130,   131,   132,   133,
   134,   135,   130,   131,   132,   133,   134,   135,   130,   131,
   132,   133,   134,   135,   130,   131,   132,   133,   134,   135,
   130,   131,   132,   133,   134,   135 ]

racc_action_check = [
    23,    23,    23,   102,   109,   243,   241,    23,    23,   204,
   204,    23,    23,    23,    23,   109,    23,   241,    23,    23,
    23,    23,    23,    23,    23,    23,    23,    23,    23,    23,
    23,    23,    23,    23,    23,    23,    23,    23,     0,    48,
    77,   102,    23,   243,   168,    77,    18,   173,   176,   216,
   206,   206,   168,   176,   216,     1,   173,     0,    48,    11,
     5,   168,    18,    89,    89,    89,     6,    23,    23,    23,
    89,    89,   173,     8,    89,    89,    89,    89,    11,    89,
     9,    89,    89,    89,    89,    89,    89,    89,    89,    89,
    89,    89,    89,    89,    89,    89,    89,    89,    89,    89,
    89,    46,   160,    46,    11,    89,    89,    11,    16,    89,
     2,    46,    17,     2,   160,   160,   160,   160,   160,   160,
    46,    22,    31,    29,    22,    31,   149,   149,   149,    30,
    89,    89,    89,   149,   149,   207,   207,   149,   149,   149,
   149,    32,   149,    41,   149,   149,   149,   149,   149,   149,
   149,   149,   149,   149,   149,   149,   149,   149,   149,   149,
   149,   149,   149,   149,    85,   127,    44,    85,   149,   127,
   127,   127,   127,   127,   127,   127,   127,   127,   127,   127,
   127,   127,   127,   127,   127,   127,   127,   127,   127,   153,
   153,   153,    45,   149,   149,   149,   153,   153,   262,   262,
   153,   153,   153,   153,    47,   153,    79,   153,   153,   153,
   153,   153,   153,   153,   153,   153,   153,   153,   153,   153,
   153,   153,   153,   153,   153,   153,   153,   126,    83,   162,
   126,   153,   162,    84,    86,    92,    92,    92,    92,    92,
    92,   100,    92,    92,    92,    92,    92,    92,    92,   103,
   106,   107,   161,   161,   161,    92,   153,   153,   153,   161,
   161,   113,   119,   161,   161,   161,   161,   124,   161,   125,
   161,   161,   161,   161,   161,   161,   161,   161,   161,   161,
   161,   161,   161,   161,   161,   161,   161,   161,   161,   161,
   188,   188,   188,   188,   161,   128,   144,   146,   147,   147,
   147,   147,   147,   147,   154,   147,   147,   147,   147,   147,
   147,   147,   155,   164,   169,   226,   226,   226,   147,   161,
   161,   161,   226,   226,   171,   178,   226,   226,   226,   226,
   187,   226,   190,   226,   226,   226,   226,   226,   226,   226,
   226,   226,   226,   226,   226,   226,   226,   226,   226,   226,
   226,   226,   226,   189,   189,   189,   189,   226,   183,   183,
   183,   183,   183,   183,   183,   183,   183,   183,   183,   183,
   183,   183,   183,   183,   183,   183,   183,   183,   258,   258,
   258,   191,   226,   226,   226,   258,   258,   192,   193,   258,
   258,   258,   258,   205,   258,   208,   258,   258,   258,   258,
   258,   258,   258,   258,   258,   258,   258,   258,   258,   258,
   258,   258,   258,   258,   258,   258,   211,    34,    34,    34,
   258,   218,    35,    35,    35,   221,   223,   231,    37,    37,
    37,   104,   104,   104,   104,   104,   104,   254,   256,   104,
   104,   104,   104,   261,    34,   258,   258,   258,    34,    35,
    38,    38,    38,    35,    99,    37,    99,   210,    34,    37,
   210,   nil,   219,    35,    99,   219,   nil,   236,   nil,    37,
   236,    34,   nil,    34,    34,    34,    35,    38,    35,    35,
    35,    38,    37,   nil,    37,    37,    37,    39,    39,    39,
   nil,    38,    90,    90,    90,    94,    94,    94,   194,   194,
   194,   194,   194,   194,   nil,   nil,    38,    38,    38,   238,
   248,   nil,   238,   248,    39,   nil,   nil,   250,    39,    90,
   250,   252,    94,    90,   252,   nil,    94,   nil,    39,    95,
    95,    95,   nil,    90,   nil,   nil,    94,    97,    97,    97,
   nil,    39,   nil,    39,    39,    39,    90,   nil,    90,    90,
    90,    94,    94,    94,   nil,   nil,    95,   105,   105,   105,
    95,   nil,   nil,   nil,    97,   108,   108,   108,    97,   nil,
    95,   195,   195,   195,   195,   195,   195,   nil,    97,   nil,
   nil,   nil,   nil,    95,   105,    95,    95,    95,   105,   nil,
   nil,    97,   108,    97,    97,    97,   108,   nil,   105,   111,
   111,   111,   nil,   nil,   nil,   nil,   108,   114,   114,   114,
   nil,   nil,   nil,   105,   105,   105,   nil,   nil,   nil,   108,
   nil,   108,   108,   108,   nil,   nil,   111,   115,   115,   115,
   111,   nil,   nil,   nil,   114,   116,   116,   116,   114,   nil,
   111,   196,   196,   196,   196,   196,   196,   nil,   114,   nil,
   nil,   nil,   nil,   111,   115,   111,   111,   111,   115,   nil,
   nil,   114,   116,   114,   114,   114,   116,   nil,   115,   117,
   117,   117,   130,   130,   130,   nil,   116,   131,   131,   131,
   nil,   115,   nil,   115,   115,   115,   nil,   nil,   nil,   116,
   nil,   116,   116,   116,   nil,   nil,   117,   nil,   nil,   130,
   117,   nil,   nil,   130,   131,   132,   132,   132,   131,   nil,
   117,   nil,   nil,   130,   133,   133,   133,   nil,   131,   nil,
   nil,   nil,   nil,   117,   nil,   117,   117,   117,   130,   130,
   130,   nil,   132,   131,   131,   131,   132,   134,   134,   134,
   nil,   133,   135,   135,   135,   133,   132,   nil,   136,   136,
   136,   nil,   nil,   nil,   nil,   133,   nil,   nil,   nil,   nil,
   nil,   132,   132,   132,   134,   nil,   nil,   nil,   134,   135,
   133,   133,   133,   135,   nil,   136,   nil,   nil,   134,   136,
   137,   137,   137,   135,   nil,   138,   138,   138,   nil,   136,
   nil,   nil,   nil,   134,   134,   134,   nil,   nil,   135,   135,
   135,   nil,   nil,   nil,   136,   136,   136,   137,   139,   139,
   139,   137,   138,   140,   140,   140,   138,   nil,   nil,   nil,
   nil,   137,   nil,   nil,   nil,   nil,   138,   nil,   nil,   nil,
   nil,   141,   141,   141,   nil,   139,   137,   137,   137,   139,
   140,   138,   138,   138,   140,   nil,   nil,   nil,   nil,   139,
   142,   142,   142,   nil,   140,   143,   143,   143,   141,   nil,
   nil,   nil,   141,   nil,   139,   139,   139,   nil,   nil,   140,
   140,   140,   141,   212,   212,   212,   nil,   142,   214,   214,
   214,   142,   143,   nil,   nil,   nil,   143,   141,   141,   141,
   nil,   142,   nil,   nil,   nil,   nil,   143,   225,   225,   225,
   212,   nil,   212,   nil,   212,   214,   142,   142,   142,   214,
   nil,   143,   143,   143,   212,   228,   228,   228,   nil,   214,
   nil,   229,   229,   229,   225,   nil,   nil,   212,   225,   212,
   212,   212,   214,   nil,   214,   214,   214,   nil,   225,   234,
   234,   234,   228,   nil,   nil,   nil,   228,   nil,   229,   nil,
   nil,   225,   229,   225,   225,   225,   228,   260,   260,   260,
   nil,   nil,   229,   nil,   nil,   nil,   234,   nil,   nil,   nil,
   234,   228,   228,   228,   nil,   nil,   nil,   229,   229,   229,
   234,   nil,   nil,   nil,   260,   nil,   nil,   nil,   260,   nil,
   nil,   nil,   nil,   234,   nil,   234,   234,   234,   260,   nil,
   nil,    81,   197,   197,   197,   197,   197,   197,   nil,   nil,
   nil,   260,   nil,   260,   260,   260,    81,   nil,    81,   nil,
    81,    81,    81,    81,    81,    81,    81,    81,    81,    81,
    81,    81,    81,    81,    81,    81,    81,    81,    81,    81,
    28,   nil,    28,   nil,    28,    28,    28,    28,    28,    28,
    28,    28,    28,    28,    28,    28,    28,    28,    28,    28,
    28,    28,    28,    28,   145,   nil,   nil,   nil,   nil,    28,
   nil,   nil,    28,   nil,   nil,   nil,   145,   145,   145,   145,
   145,   145,   nil,   145,   145,   145,   145,   145,   145,   145,
   198,   198,   198,   198,   198,   198,   145,   240,   240,   240,
   240,   240,   240,   240,   240,   240,   240,   240,   240,   240,
   240,   240,   240,   240,   240,   240,   240,   nil,   nil,   nil,
   nil,   nil,   240,   nil,   nil,   240,    25,    25,    25,    25,
    25,    25,    25,    25,    25,    25,    25,    25,    25,    25,
    25,    25,    25,    25,    25,    25,   nil,   nil,   nil,   nil,
    25,   120,   120,   120,   120,   120,   120,   120,   120,   120,
   120,   120,   120,   120,   120,   120,   120,   120,   120,   120,
   120,   nil,   nil,   nil,   nil,   120,   184,   184,   184,   184,
   184,   184,   184,   184,   184,   184,   184,   184,   184,   184,
   184,   184,   184,   184,   184,   184,   209,   209,   209,   209,
   209,   209,   209,   209,   209,   209,   209,   209,   209,   209,
   209,   209,   209,   209,   209,   209,   237,   237,   237,   237,
   237,   237,   237,   237,   237,   237,   237,   237,   237,   237,
   237,   237,   237,   237,   237,   237,   199,   199,   199,   199,
   199,   199,   200,   200,   200,   200,   200,   200,   201,   201,
   201,   201,   201,   201,   245,   245,   245,   245,   245,   245,
   246,   246,   246,   246,   246,   246 ]

racc_action_pointer = [
    36,    55,    63,   nil,   nil,    58,    20,   nil,    27,    80,
   nil,    57,   nil,   nil,   nil,   nil,    94,    70,    -7,   nil,
   nil,   nil,    74,    -4,   nil,  1104,   nil,   nil,  1022,    77,
   126,    75,   135,   nil,   402,   407,   nil,   413,   435,   472,
   nil,    97,   nil,   nil,    96,   135,    59,   143,    -3,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    -3,   nil,   160,
   nil,   998,   nil,   182,   187,   117,   173,   nil,   nil,    59,
   477,   nil,   180,   nil,   480,   514,   nil,   522,   nil,   412,
   199,   nil,    -6,   235,   376,   542,   236,   237,   550,   -42,
   nil,   584,   nil,   215,   592,   612,   620,   654,   nil,   215,
  1129,   nil,   nil,   nil,   225,   255,   180,   147,   289,   nil,
   657,   662,   690,   699,   722,   727,   733,   765,   770,   793,
   798,   816,   835,   840,   237,  1021,   254,   243,   nil,   122,
   nil,   nil,   nil,   185,   258,   266,   nil,   nil,   nil,   nil,
    59,   248,   182,   nil,   265,   nil,   nil,   nil,     0,   253,
   nil,   263,   nil,     3,   nil,   nil,     5,   nil,   280,   nil,
   nil,   nil,   nil,   336,  1154,   nil,   nil,   284,   233,   296,
   273,   322,   328,   329,   443,   516,   586,   947,  1035,  1181,
  1187,  1193,   nil,   nil,     2,   390,   -13,    70,   392,  1174,
   410,   370,   858,   nil,   863,   nil,     6,   nil,   418,   415,
   nil,   368,   nil,   423,   nil,   882,   311,   nil,   900,   906,
   nil,   424,   nil,   nil,   924,   nil,   420,  1194,   462,   nil,
  1075,   -40,   nil,    -4,   nil,  1199,  1205,   nil,   465,   nil,
   470,   nil,   474,   nil,   389,   nil,   394,   nil,   374,   nil,
   942,   397,   191,   nil,   nil,   nil ]

racc_action_default = [
    -2,  -155,  -148,    -3,    -5,    -6,  -155,   -19,  -155,  -155,
    -1,  -149,  -150,  -152,  -153,   -20,  -155,   -86,   -85,   266,
    -4,  -151,  -155,   -23,   -87,  -155,   -83,   -84,  -155,  -155,
  -155,  -148,   -24,   -26,  -155,  -155,   -29,  -155,  -155,  -155,
   -34,  -155,   -36,   -37,  -155,   -60,  -122,  -115,  -122,   -77,
   -78,   -79,   -80,   -81,   -82,  -116,  -118,  -128,  -129,  -130,
  -131,  -132,  -133,  -134,  -135,  -136,  -137,  -138,  -139,  -140,
  -141,  -142,  -143,  -144,  -145,  -146,  -147,  -155,   -89,  -155,
   -92,  -155,    -8,  -155,  -155,  -155,  -155,   -21,   -22,  -149,
  -155,   -27,   -93,   -94,  -155,  -155,  -103,  -155,  -115,  -122,
  -122,   -28,  -155,  -155,  -155,  -155,  -155,   -38,  -155,  -155,
   -61,  -155,  -117,  -155,  -124,  -155,  -155,  -155,  -119,  -155,
  -155,   -91,    -7,    -9,  -155,  -155,   -12,  -155,   -25,   -31,
  -155,  -155,  -155,  -155,  -155,  -155,  -155,  -155,  -155,  -155,
  -155,  -155,  -155,  -155,  -101,  -155,  -155,  -113,  -114,   -23,
   -53,   -54,  -154,   -23,  -155,  -155,   -49,   -50,   -51,   -52,
  -155,   -23,  -148,   -46,   -59,   -62,   -65,   -66,   -67,   -68,
   -69,  -155,   -74,   -85,  -120,  -121,  -155,  -125,  -155,   -75,
   -76,   -88,   -90,   -16,   -40,   -13,   -14,  -155,   -95,   -96,
   -97,   -98,   -99,  -100,  -104,  -105,  -106,  -107,  -108,  -109,
  -110,  -111,  -102,  -112,   -55,  -155,  -155,  -155,  -155,   -40,
  -149,  -155,  -155,  -123,  -155,  -127,  -155,   -17,  -155,  -148,
   -41,   -60,   -15,  -155,   -56,  -155,   -23,   -32,  -155,  -155,
   -33,  -155,   -63,   -64,   -71,  -126,  -155,  -155,  -155,   -39,
  -149,  -155,   -30,  -155,   -58,   -47,   -48,   -35,  -155,   -72,
   -10,   -18,   -11,   -42,   -43,   -44,   -67,   -68,   -23,   -70,
  -155,  -155,   -55,   -73,   -45,   -57 ]

racc_goto_table = [
    21,    30,    47,    44,    79,    17,    10,    83,    11,   109,
   149,   170,   166,   155,    78,   154,   167,    21,   223,    48,
    82,    91,   101,   118,   102,   218,   106,    85,    28,     3,
   146,     1,   148,     2,    81,    88,   216,    89,   185,    15,
    20,    23,   128,   103,   253,   254,   181,   164,   248,    24,
   231,    77,   176,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    83,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    47,    44,
   nil,   nil,   nil,   123,   nil,   118,   265,   129,    21,   104,
    85,   nil,   nil,   nil,   nil,    48,   nil,   nil,   169,   nil,
   nil,   126,   175,   nil,   nil,   163,   nil,   nil,   172,    79,
   nil,   177,   178,   nil,   180,   171,   186,   nil,   nil,   182,
   174,   nil,   nil,   170,   233,    21,   229,   228,   232,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   204,    47,    44,
   nil,   205,    47,    44,   nil,   144,   145,   nil,   147,   208,
    47,    44,   nil,   nil,   255,    48,   160,   nil,   nil,    48,
   nil,   258,   nil,   nil,   nil,   nil,   nil,    48,   nil,   nil,
   nil,   nil,   217,   221,   264,   nil,   209,   nil,   210,   nil,
   nil,   188,   189,   190,   191,   192,   193,   194,   195,   196,
   197,   198,   199,   200,   201,   241,   nil,   nil,   221,   nil,
   169,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    21,
   nil,   235,   nil,   nil,   244,    47,    44,   171,   nil,   nil,
   nil,   nil,   243,   nil,   nil,   nil,   251,   nil,   nil,   221,
   257,   249,    48,   239,   nil,   240,   nil,   nil,   nil,    21,
   nil,   nil,   nil,   nil,   nil,   nil,   262,    47,    44,    21,
   257,    21,   250,   nil,   252,   nil,   nil,   263,   nil,   nil,
   nil,   nil,   nil,   nil,    48,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   245,
   246 ]

racc_goto_check = [
    53,    18,    42,    34,    10,    16,     3,    10,     5,    31,
    24,    23,    33,    37,    48,    36,    41,    53,    25,    44,
     9,    22,    22,    50,    22,    12,    22,    13,     5,     4,
    49,     1,    49,     2,     8,     3,    11,     5,    14,    15,
     4,    17,    20,    26,    30,    32,    38,    40,    43,    46,
    12,    47,    52,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    10,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    42,    34,
   nil,   nil,   nil,     9,   nil,    50,    25,    22,    53,    35,
    13,   nil,   nil,   nil,   nil,    44,   nil,   nil,    42,   nil,
   nil,     5,    42,   nil,   nil,    22,   nil,   nil,    22,    10,
   nil,    22,    22,   nil,    22,    44,    10,   nil,   nil,    48,
    16,   nil,   nil,    23,    33,    53,    37,    36,    41,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,    42,    34,
   nil,    18,    42,    34,   nil,    35,    35,   nil,    35,    18,
    42,    34,   nil,   nil,    33,    44,    35,   nil,   nil,    44,
   nil,    24,   nil,   nil,   nil,   nil,   nil,    44,   nil,   nil,
   nil,   nil,    10,    10,    33,   nil,     3,   nil,     5,   nil,
   nil,    35,    35,    35,    35,    35,    35,    35,    35,    35,
    35,    35,    35,    35,    35,    31,   nil,   nil,    10,   nil,
    42,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    53,
   nil,    22,   nil,   nil,    18,    42,    34,    44,   nil,   nil,
   nil,   nil,    22,   nil,   nil,   nil,    10,   nil,   nil,    10,
    42,    22,    44,     3,   nil,     5,   nil,   nil,   nil,    53,
   nil,   nil,   nil,   nil,   nil,   nil,    18,    42,    34,    53,
    42,    53,     5,   nil,     5,   nil,   nil,    22,   nil,   nil,
   nil,   nil,   nil,   nil,    44,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    35,
    35 ]

racc_goto_pointer = [
   nil,    31,    33,     4,    29,     6,   nil,   nil,     6,    -8,
   -21,  -147,  -159,    -1,   -89,    34,    -3,    24,   -22,   nil,
   -47,   nil,   -13,   -98,   -92,  -186,     5,   nil,   nil,   nil,
  -196,   -36,  -196,   -97,   -20,    41,   -89,   -91,   -73,   nil,
   -62,   -93,   -21,  -186,    -4,   nil,    32,    26,   -11,   -65,
   -25,   nil,   -62,   -11 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,     4,     5,   nil,   nil,
    45,   nil,   nil,    43,   nil,     7,   nil,   nil,   nil,    31,
    32,    33,   179,    36,   nil,   nil,   nil,    40,    42,   219,
   220,   nil,   nil,   nil,    96,    92,   nil,   nil,   151,   224,
   nil,   nil,    98,   nil,   100,    55,   nil,   nil,   nil,    93,
   112,    56,   nil,    12 ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 77, :_reduce_1,
  0, 78, :_reduce_2,
  1, 78, :_reduce_3,
  3, 78, :_reduce_4,
  1, 80, :_reduce_5,
  1, 80, :_reduce_6,
  6, 82, :_reduce_7,
  1, 84, :_reduce_8,
  2, 84, :_reduce_9,
  6, 85, :_reduce_10,
  6, 85, :_reduce_11,
  2, 85, :_reduce_none,
  4, 89, :_reduce_13,
  1, 90, :_reduce_none,
  2, 90, :_reduce_15,
  0, 87, :_reduce_16,
  1, 87, :_reduce_17,
  3, 87, :_reduce_18,
  1, 83, :_reduce_19,
  2, 83, :_reduce_20,
  5, 91, :_reduce_21,
  2, 94, :_reduce_22,
  0, 95, :_reduce_23,
  1, 95, :_reduce_24,
  3, 95, :_reduce_25,
  1, 96, :_reduce_26,
  2, 96, :_reduce_27,
  2, 96, :_reduce_28,
  1, 96, :_reduce_29,
  6, 96, :_reduce_30,
  3, 96, :_reduce_31,
  5, 96, :_reduce_32,
  5, 96, :_reduce_33,
  1, 96, :_reduce_34,
  6, 96, :_reduce_35,
  1, 96, :_reduce_36,
  1, 96, :_reduce_none,
  2, 104, :_reduce_38,
  2, 88, :_reduce_39,
  0, 105, :_reduce_40,
  1, 105, :_reduce_41,
  3, 105, :_reduce_42,
  3, 106, :_reduce_43,
  1, 108, :_reduce_44,
  3, 108, :_reduce_45,
  3, 103, :_reduce_46,
  5, 102, :_reduce_47,
  5, 102, :_reduce_48,
  1, 112, :_reduce_none,
  1, 112, :_reduce_none,
  1, 113, :_reduce_none,
  1, 113, :_reduce_none,
  1, 100, :_reduce_none,
  1, 100, :_reduce_none,
  0, 101, :_reduce_55,
  1, 101, :_reduce_56,
  5, 101, :_reduce_57,
  2, 115, :_reduce_58,
  3, 97, :_reduce_59,
  0, 107, :_reduce_60,
  1, 107, :_reduce_61,
  2, 107, :_reduce_62,
  3, 116, :_reduce_63,
  3, 116, :_reduce_64,
  1, 116, :_reduce_65,
  1, 116, :_reduce_66,
  1, 109, :_reduce_67,
  1, 109, :_reduce_68,
  1, 117, :_reduce_none,
  5, 117, :_reduce_70,
  0, 119, :_reduce_71,
  1, 119, :_reduce_72,
  3, 119, :_reduce_73,
  3, 99, :_reduce_74,
  3, 99, :_reduce_75,
  3, 99, :_reduce_76,
  1, 121, :_reduce_77,
  1, 121, :_reduce_78,
  1, 121, :_reduce_79,
  1, 121, :_reduce_80,
  1, 121, :_reduce_81,
  1, 121, :_reduce_82,
  2, 92, :_reduce_83,
  2, 92, :_reduce_84,
  1, 92, :_reduce_85,
  0, 93, :_reduce_86,
  1, 93, :_reduce_none,
  4, 122, :_reduce_88,
  1, 123, :_reduce_89,
  3, 123, :_reduce_90,
  2, 124, :_reduce_91,
  1, 124, :_reduce_92,
  1, 98, :_reduce_93,
  1, 98, :_reduce_94,
  3, 111, :_reduce_95,
  3, 111, :_reduce_96,
  3, 111, :_reduce_97,
  3, 111, :_reduce_98,
  3, 111, :_reduce_99,
  3, 111, :_reduce_100,
  2, 111, :_reduce_101,
  3, 111, :_reduce_102,
  1, 111, :_reduce_103,
  3, 125, :_reduce_104,
  3, 125, :_reduce_105,
  3, 125, :_reduce_106,
  3, 125, :_reduce_107,
  3, 125, :_reduce_108,
  3, 125, :_reduce_109,
  3, 125, :_reduce_110,
  3, 125, :_reduce_111,
  3, 125, :_reduce_112,
  2, 125, :_reduce_113,
  2, 125, :_reduce_114,
  1, 110, :_reduce_115,
  1, 110, :_reduce_116,
  2, 110, :_reduce_117,
  1, 110, :_reduce_none,
  2, 127, :_reduce_119,
  3, 120, :_reduce_120,
  3, 120, :_reduce_121,
  0, 126, :_reduce_122,
  3, 126, :_reduce_123,
  0, 128, :_reduce_124,
  1, 128, :_reduce_125,
  3, 128, :_reduce_126,
  4, 118, :_reduce_127,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_none,
  1, 86, :_reduce_147,
  0, 79, :_reduce_148,
  1, 79, :_reduce_149,
  1, 81, :_reduce_150,
  2, 81, :_reduce_151,
  1, 129, :_reduce_152,
  1, 129, :_reduce_none,
  1, 114, :_reduce_154 ]

racc_reduce_n = 155

racc_shift_n = 266

racc_token_table = {
  false => 0,
  :error => 1,
  :kDEF => 2,
  :kEND => 3,
  :kRETURN => 4,
  :kPRINT => 5,
  :kIF => 6,
  :kELSIF => 7,
  :kELSE => 8,
  :kTHEN => 9,
  :kSTATIC_ARRAY => 10,
  :kFOR => 11,
  :kWHILE => 12,
  :kDOT_EACH => 13,
  :kDO => 14,
  :kTRUE => 15,
  :kFALSE => 16,
  :kNIL => 17,
  :kSTRUCT => 18,
  :kUNION => 19,
  :kALIAS => 20,
  :kLIB => 21,
  :kDTYPE_UINT => 22,
  :kDTYPE_LINT => 23,
  :kDTYPE_LLINT => 24,
  :kDTYPE_CHAR => 25,
  :kDTYPE_I8 => 26,
  :kDTYPE_I16 => 27,
  :kDTYPE_I32 => 28,
  :kDTYPE_I64 => 29,
  :kDTYPE_UI8 => 30,
  :kDTYPE_UI16 => 31,
  :kDTYPE_UI32 => 32,
  :kDTYPE_UI64 => 33,
  :kDTYPE_INT => 34,
  :kDTYPE_F32 => 35,
  :kDTYPE_F64 => 36,
  :kDTYPE_LF64 => 37,
  :kDTYPE_ROBJ => 38,
  :kDTYPE_ULINT => 39,
  :kDTYPE_ULLINT => 40,
  :tCUSTOM_DTYPE => 41,
  :tLPAREN => 42,
  :tRPAREN => 43,
  :tLSQUARE => 44,
  :tRSQUARE => 45,
  :tIDENTIFIER => 46,
  :tNL => 47,
  :tCOMMA => 48,
  :tSQUOTE => 49,
  :tSCOLON => 50,
  :EOF => 51,
  :tDOT => 52,
  :tQMARK => 53,
  :tSTART_LINE => 54,
  :tPLUS => 55,
  :tMINUS => 56,
  :tSTAR => 57,
  :tDIVIDE => 58,
  :tEXPO => 59,
  :tMODULUS => 60,
  :tASSIGN => 61,
  :tEQ => 62,
  :tLT => 63,
  :tLTEQ => 64,
  :tGT => 65,
  :tGTEQ => 66,
  :tANDOP => 67,
  :tOROP => 68,
  :tBANG => 69,
  :tOP_ASSIGN => 70,
  :tINTEGER => 71,
  :tFLOAT => 72,
  :tSINGLE_CHAR => 73,
  :UMINUS => 74,
  :tNEQ => 75 }

racc_nt_base = 76

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "kDEF",
  "kEND",
  "kRETURN",
  "kPRINT",
  "kIF",
  "kELSIF",
  "kELSE",
  "kTHEN",
  "kSTATIC_ARRAY",
  "kFOR",
  "kWHILE",
  "kDOT_EACH",
  "kDO",
  "kTRUE",
  "kFALSE",
  "kNIL",
  "kSTRUCT",
  "kUNION",
  "kALIAS",
  "kLIB",
  "kDTYPE_UINT",
  "kDTYPE_LINT",
  "kDTYPE_LLINT",
  "kDTYPE_CHAR",
  "kDTYPE_I8",
  "kDTYPE_I16",
  "kDTYPE_I32",
  "kDTYPE_I64",
  "kDTYPE_UI8",
  "kDTYPE_UI16",
  "kDTYPE_UI32",
  "kDTYPE_UI64",
  "kDTYPE_INT",
  "kDTYPE_F32",
  "kDTYPE_F64",
  "kDTYPE_LF64",
  "kDTYPE_ROBJ",
  "kDTYPE_ULINT",
  "kDTYPE_ULLINT",
  "tCUSTOM_DTYPE",
  "tLPAREN",
  "tRPAREN",
  "tLSQUARE",
  "tRSQUARE",
  "tIDENTIFIER",
  "tNL",
  "tCOMMA",
  "tSQUOTE",
  "tSCOLON",
  "EOF",
  "tDOT",
  "tQMARK",
  "tSTART_LINE",
  "tPLUS",
  "tMINUS",
  "tSTAR",
  "tDIVIDE",
  "tEXPO",
  "tMODULUS",
  "tASSIGN",
  "tEQ",
  "tLT",
  "tLTEQ",
  "tGT",
  "tGTEQ",
  "tANDOP",
  "tOROP",
  "tBANG",
  "tOP_ASSIGN",
  "tINTEGER",
  "tFLOAT",
  "tSINGLE_CHAR",
  "UMINUS",
  "tNEQ",
  "$start",
  "program",
  "topstmts",
  "opt_terms",
  "topstmt",
  "terms",
  "c_bindings",
  "methods",
  "c_declarations",
  "c_declaration",
  "dtype",
  "dtype_list",
  "var_decl_stmts",
  "alias_stmt",
  "aliased_type",
  "ruby_method",
  "f_name",
  "f_opt_arglist",
  "compstmt",
  "stmts",
  "stmt",
  "var_decl_or_init",
  "expr",
  "normal_init",
  "then",
  "if_tail",
  "for_expr",
  "op_assign",
  "forward_declaration",
  "var_decls",
  "var_decl",
  "opt_star",
  "var_names",
  "normal_decl",
  "atomic_value",
  "expr_value",
  "lt_or_lteq",
  "gt_or_gteq",
  "eol",
  "opt_else",
  "decl_or_init",
  "var_init",
  "array_ref",
  "array_list",
  "method_or_attr",
  "literal",
  "f_arglist",
  "f_args",
  "f_normal_arg",
  "expr_cmp",
  "command_opt_args",
  "command_call",
  "command_arg_list",
  "term" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.racc', 36)
  def _reduce_1(val, _values, result)
     result = Node.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 39)
  def _reduce_2(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 40)
  def _reduce_3(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 41)
  def _reduce_4(val, _values, result)
     result = [*val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 44)
  def _reduce_5(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 45)
  def _reduce_6(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 50)
  def _reduce_7(val, _values, result)
            result = CBindings.new val[1], val[4]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 54)
  def _reduce_8(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 55)
  def _reduce_9(val, _values, result)
     result = [*val[0], val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 60)
  def _reduce_10(val, _values, result)
            result = CBindings::CFunctionDecl.new val[0], val[1], val[3]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 64)
  def _reduce_11(val, _values, result)
            result = Statement::CStructOrUnionDef.new val[0], val[1], val[3]
      
    result
  end
.,.,

# reduce 12 omitted

module_eval(<<'.,.,', 'parser.racc', 71)
  def _reduce_13(val, _values, result)
            add_dtype_to_lexer val[1]
        result = Statement::Alias.new val[1], val[3]
      
    result
  end
.,.,

# reduce 14 omitted

module_eval(<<'.,.,', 'parser.racc', 77)
  def _reduce_15(val, _values, result)
     result = val.join 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 80)
  def _reduce_16(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 81)
  def _reduce_17(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 82)
  def _reduce_18(val, _values, result)
     result = [*val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 85)
  def _reduce_19(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 86)
  def _reduce_20(val, _values, result)
     result = [*val[0], val[1]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 91)
  def _reduce_21(val, _values, result)
            result = RubyMethodDef.new(val[1], val[2], val[3])
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 95)
  def _reduce_22(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 98)
  def _reduce_23(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 99)
  def _reduce_24(val, _values, result)
     result = [*val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 100)
  def _reduce_25(val, _values, result)
     result = [*val[0], *val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 106)
  def _reduce_26(val, _values, result)
            variables = []
        dtype = val[0][:dtype]
        val[0][:decl_or_init].each do |di|
          variables << node_variable(dtype, di)
        end

        result = variables
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 114)
  def _reduce_27(val, _values, result)
     result = Statement::Return.new val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 115)
  def _reduce_28(val, _values, result)
     result = Statement::Print.new val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 118)
  def _reduce_29(val, _values, result)
            match = val[0]
        result = Statement::Assign.new match[:name], match[:value]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 123)
  def _reduce_30(val, _values, result)
            result = Statement::IfBlock.new val[1], [*val[3]], [*val[4]]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 125)
  def _reduce_31(val, _values, result)
     result = Statement::IfBlock.new val[2], [*val[0]], [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 128)
  def _reduce_32(val, _values, result)
            result = Statement::For.new *val[1], val[3]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 130)
  def _reduce_33(val, _values, result)
     result = Statement::While.new val[1], val[3] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 131)
  def _reduce_34(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 134)
  def _reduce_35(val, _values, result)
            add_dtype_to_lexer val[1]
        result = Statement::CStructOrUnionDef.new val[0], val[1], val[4]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 137)
  def _reduce_36(val, _values, result)
    
    result
  end
.,.,

# reduce 37 omitted

module_eval(<<'.,.,', 'parser.racc', 143)
  def _reduce_38(val, _values, result)
          val.flatten!
      add_dtype_to_lexer val[1]
      result = Statement::ForwardDecl.new val[0], val[1]
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 151)
  def _reduce_39(val, _values, result)
            declarations = []
        val[0].each do |data|
          dtype = data[:dtype]
          data[:decl].each do |d|
            declarations << node_variable(dtype, d)
          end
        end

        result = declarations
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 163)
  def _reduce_40(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 164)
  def _reduce_41(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 165)
  def _reduce_42(val, _values, result)
     result = [*val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 170)
  def _reduce_43(val, _values, result)
          val[2].each { |d| d[:pointer] = val[1] }
      result = {
        dtype: val[0],
        decl:  val[2]
      }
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 178)
  def _reduce_44(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 179)
  def _reduce_45(val, _values, result)
     result = [*val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 184)
  def _reduce_46(val, _values, result)
            #  TODO: error if lvalue is a literal
        result = op_assign val
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 189)
  def _reduce_47(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 190)
  def _reduce_48(val, _values, result)
     result = val 
    result
  end
.,.,

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

module_eval(<<'.,.,', 'parser.racc', 202)
  def _reduce_55(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 203)
  def _reduce_56(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 206)
  def _reduce_57(val, _values, result)
            result = Statement::IfBlock::Elsif.new val[1], [*val[3]], [*val[4]]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 210)
  def _reduce_58(val, _values, result)
     result = Statement::IfBlock::Else.new val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 215)
  def _reduce_59(val, _values, result)
            val[2][0][:pointer] = val[1]
        result = {
          dtype: val[0],
          decl_or_init: val[2]
        }
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 223)
  def _reduce_60(val, _values, result)
     result = nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 224)
  def _reduce_61(val, _values, result)
     
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 225)
  def _reduce_62(val, _values, result)
     result = val.join 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 228)
  def _reduce_63(val, _values, result)
     result = [*val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 229)
  def _reduce_64(val, _values, result)
     result = [*val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 230)
  def _reduce_65(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 231)
  def _reduce_66(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 234)
  def _reduce_67(val, _values, result)
     result = { name: val[0] } 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 235)
  def _reduce_68(val, _values, result)
     result = { name: val[0] } 
    result
  end
.,.,

# reduce 69 omitted

module_eval(<<'.,.,', 'parser.racc', 241)
  def _reduce_70(val, _values, result)
          result = { name: val[0], value: val[3] }
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 245)
  def _reduce_71(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 246)
  def _reduce_72(val, _values, result)
     result = [*val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 247)
  def _reduce_73(val, _values, result)
     result = [*val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 250)
  def _reduce_74(val, _values, result)
     result = { name: val[0], value: val[2] } 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 251)
  def _reduce_75(val, _values, result)
     result = { name: val[0], value: val[2] } 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 254)
  def _reduce_76(val, _values, result)
          result = {
        name: Expression::CommandCall.new(val[0][0], val[0][1], []),
        value: val[2]
      }
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 261)
  def _reduce_77(val, _values, result)
     result = Expression::Literal::Int.new val[0]    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 262)
  def _reduce_78(val, _values, result)
     result = Expression::Literal::Double.new val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 263)
  def _reduce_79(val, _values, result)
     result = Expression::Literal::Char.new val[0]   
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 264)
  def _reduce_80(val, _values, result)
     result = Expression::Literal::True.new 'Qtrue' 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 265)
  def _reduce_81(val, _values, result)
     result = Expression::Literal::False.new 'Qfalse' 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 266)
  def _reduce_82(val, _values, result)
     result = Expression::Literal::Nil.new 'Qnil' 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 269)
  def _reduce_83(val, _values, result)
     result = "#{val[0]}#{val[1]}" 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 270)
  def _reduce_84(val, _values, result)
     result = "#{val[0]}#{val[1]}" 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 271)
  def _reduce_85(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 274)
  def _reduce_86(val, _values, result)
     result = [] 
    result
  end
.,.,

# reduce 87 omitted

module_eval(<<'.,.,', 'parser.racc', 278)
  def _reduce_88(val, _values, result)
     result = ArgumentList.new val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 281)
  def _reduce_89(val, _values, result)
     result = [val[0]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 284)
  def _reduce_90(val, _values, result)
            result = [*val[0], val[2]]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 288)
  def _reduce_91(val, _values, result)
     result = CBaseType.new val[0], val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 289)
  def _reduce_92(val, _values, result)
     result = CBaseType.new 'object', val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 292)
  def _reduce_93(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 293)
  def _reduce_94(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 296)
  def _reduce_95(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 297)
  def _reduce_96(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 298)
  def _reduce_97(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 299)
  def _reduce_98(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 300)
  def _reduce_99(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 301)
  def _reduce_100(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 302)
  def _reduce_101(val, _values, result)
     result = unary_op val  
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 303)
  def _reduce_102(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 304)
  def _reduce_103(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 307)
  def _reduce_104(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 308)
  def _reduce_105(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 309)
  def _reduce_106(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 310)
  def _reduce_107(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 311)
  def _reduce_108(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 312)
  def _reduce_109(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 313)
  def _reduce_110(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 314)
  def _reduce_111(val, _values, result)
     result = binary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 315)
  def _reduce_112(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 316)
  def _reduce_113(val, _values, result)
     result = unary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 317)
  def _reduce_114(val, _values, result)
     result = unary_op val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 320)
  def _reduce_115(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 321)
  def _reduce_116(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 324)
  def _reduce_117(val, _values, result)
            args = val[1]
        result =
        if args.empty?
          Expression::Name.new val[0]
        else
          Expression::CommandCall.new nil, val[0], args
        end
      
    result
  end
.,.,

# reduce 118 omitted

module_eval(<<'.,.,', 'parser.racc', 337)
  def _reduce_119(val, _values, result)
            args = ArgumentList.new val[1]
        result = Expression::CommandCall.new val[0][0], val[0][1], args
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 344)
  def _reduce_120(val, _values, result)
            name = Expression::Name.new val[0]
        result = [name, val[2]]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 349)
  def _reduce_121(val, _values, result)
          name = Expression::Name.new val[0]
      result = [name, val[2]]
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 355)
  def _reduce_122(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 356)
  def _reduce_123(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 359)
  def _reduce_124(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 360)
  def _reduce_125(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 361)
  def _reduce_126(val, _values, result)
     result = [*val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 366)
  def _reduce_127(val, _values, result)
            result = Expression::ArrayRef.new val[0], val[2]
      
    result
  end
.,.,

# reduce 128 omitted

# reduce 129 omitted

# reduce 130 omitted

# reduce 131 omitted

# reduce 132 omitted

# reduce 133 omitted

# reduce 134 omitted

# reduce 135 omitted

# reduce 136 omitted

# reduce 137 omitted

# reduce 138 omitted

# reduce 139 omitted

# reduce 140 omitted

# reduce 141 omitted

# reduce 142 omitted

# reduce 143 omitted

# reduce 144 omitted

# reduce 145 omitted

# reduce 146 omitted

module_eval(<<'.,.,', 'parser.racc', 375)
  def _reduce_147(val, _values, result)
            result = val[0]
      
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 379)
  def _reduce_148(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 380)
  def _reduce_149(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 383)
  def _reduce_150(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 384)
  def _reduce_151(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.racc', 387)
  def _reduce_152(val, _values, result)
    
    result
  end
.,.,

# reduce 153 omitted

module_eval(<<'.,.,', 'parser.racc', 391)
  def _reduce_154(val, _values, result)
    result = val[0]
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Rubex
