/* C extension for expressions.
This file in generated by Rubex. Do not change!
*/
#include <ruby.h>
#include <stdint.h>

VALUE __rubex_f_adder (int argc, VALUE* argv, VALUE __rubex_arg_self);
VALUE __rubex_f_adder (int argc, VALUE* argv, VALUE __rubex_arg_self)
{
  int __rubex_arg_left;
  float __rubex_arg_right;
  float __rubex_v_mid;
  float __rubex_v_t;
  float __rubex_v_z;
  VALUE __rubex_v_rr;
  if (argc != 2)
  {
    rb_raise(rb_eArgError, "Need 2 args, not %d", argc);
  }
  __rubex_arg_left=NUM2INT(argv[0])  ;
  __rubex_arg_right=(float)NUM2DBL(argv[1])  ;
  __rubex_v_mid = (float)(( __rubex_arg_left - __rubex_arg_right ));
  __rubex_v_t = (float)(( ( - ( __rubex_v_mid / 3 ) * ( __rubex_arg_left + __rubex_arg_right ) ) - ( __rubex_arg_left / __rubex_v_mid ) ));
  __rubex_v_z = ( __rubex_v_t - 3 );
  __rubex_v_rr = INT2NUM(( -3 - 545 ));
  return   __rubex_v_rr;
}

void Init_expressions (void);
void Init_expressions (void)
{
  rb_define_method(rb_cObject ,"adder", __rubex_f_adder, -1);
}
