/* C extension for static_array.
This file in generated by Rubex. Do not change!
*/
#include <ruby.h>
#include <stdint.h>

VALUE __rubex_f_static_array (int argc, VALUE* argv, VALUE __rubex_arg_self);
VALUE __rubex_f_static_array (int argc, VALUE* argv, VALUE __rubex_arg_self)
{
  int8_t __rubex_v_size;
  int32_t __rubex_arr_a[10];
  int32_t __rubex_arr_c[32];
  int64_t __rubex_arr_b[5] = {1,2,3,4,5};
  int64_t __rubex_arr_t[4] = {4,6,2,12};
  if (argc != 0)
  {
    rb_raise(rb_eArgError, "Need 0 args, not %d", argc);
  }
  __rubex_v_size = (int8_t)(54);
  int32_t __rubex_arr_e[__rubex_v_size];
  __rubex_arr_a[2] = 443;
  printf("%d", __rubex_arr_a[2]);
  if (( __rubex_arr_a[2] == 443 )) 
  {
    __rubex_arr_b[4] = 123;

  }
  __rubex_arr_e[53] = 4311;
  printf("%d", __rubex_arr_e[53]);
  printf("%ld", __rubex_arr_b[4]);
  return   LONG2NUM(__rubex_arr_b[4]);
}

void Init_static_array (void);
void Init_static_array (void)
{
  rb_define_method(rb_cObject ,"static_array", __rubex_f_static_array, -1);
}
