/* C extension for struct.
This file in generated by Rubex. Do not change!
*/
#include <ruby.h>
#include <stdint.h>

VALUE __rubex_f_structure (int argc, VALUE* argv, VALUE __rubex_arg_self);
VALUE __rubex_f_structure (int argc, VALUE* argv, VALUE __rubex_arg_self)
{
  typedef struct other_node __rubex_t_other_node;
  typedef struct node
  {
    int32_t __rubex_v_a;
    int32_t __rubex_v_b;
    __rubex_t_other_node* __rubex_ptr_other;
    float __rubex_arr_c[10];
  } __rubex_t_node;

  typedef struct other_node
  {
    int64_t __rubex_v_a;
    int64_t __rubex_v_b;
    char* __rubex_ptr_str;
  } __rubex_t_other_node;

  VALUE __rubex_arg_a;
  int32_t __rubex_arg_b;
  int32_t __rubex_arg_c;
  __rubex_t_node __rubex_v_n;
  __rubex_t_other_node __rubex_v_shell;
  int32_t __rubex_v_i;
  int32_t __rubex_arr_f[10];
  if (argc != 3)
  {
    rb_raise(rb_eArgError, "Need 3 args, not %d", argc);
  }
  __rubex_arg_a=argv[0]  ;
  __rubex_arg_b=(int32_t)NUM2INT(argv[1])  ;
  __rubex_arg_c=(int32_t)NUM2INT(argv[2])  ;
  __rubex_v_n.__rubex_v_a = __rubex_arg_b;
  __rubex_v_n.__rubex_v_b = __rubex_arg_c;
  __rubex_v_shell.__rubex_ptr_str = StringValueCStr(__rubex_arg_a);
  __rubex_v_shell.__rubex_v_a = 666;
  __rubex_v_shell.__rubex_v_b = 555;
  for (__rubex_v_i = 0; __rubex_v_i < 10; __rubex_v_i++)
  {
    __rubex_v_n.__rubex_arr_c[__rubex_v_i] = ( __rubex_v_i * 43 );
    __rubex_arr_f[__rubex_v_i] = ( __rubex_v_i + 4 );
  }
  printf("%f", __rubex_v_n.__rubex_arr_c[7]);
  return   LONG2NUM(__rubex_v_shell.__rubex_v_a);
}

void Init_struct (void);
void Init_struct (void)
{
  rb_define_method(rb_cObject ,"structure", __rubex_f_structure, -1);
}
