/* C extension for rcsv.
This file in generated by Rubex::Compiler. Do not change!
File generation time: 2017-08-11 17:27:08 +0530.*/

#include <ruby.h>
#include <stdint.h>
#include <stdbool.h>
#include <ruby.h>
#include <ruby/encoding.h>
#include <stdlib.h>
#include "csv.h"

#define __rubex_INT2BOOL(arg) (arg ? Qtrue : Qfalse)



typedef struct rcsv_metadata
{
  int __rubex_v_row_as_hash;
  int __rubex_v_empty_field_is_nil;
  size_t __rubex_v_offset_rows;
  int __rubex_v_encoding_index;
  char* __rubex_ptr_row_conversions;
  VALUE* __rubex_ptr_only_rows;
  VALUE* __rubex_ptr_except_rows;
  VALUE* __rubex_ptr_row_defaults;
  VALUE* __rubex_ptr_column_names;
  size_t __rubex_v_num_row_conversions;
  size_t __rubex_v_num_only_rows;
  size_t __rubex_v_num_except_rows;
  size_t __rubex_v_num_row_defaults;
  size_t __rubex_v_num_columns;
  int __rubex_v_skip_current_row;
  size_t __rubex_v_current_col;
  size_t __rubex_v_current_row;
  VALUE __rubex_v_last_entry;
  VALUE __rubex_v_result;
} __rubex_t_Object_rcsv_metadata;



VALUE rb_cObject;
VALUE rb_eStandardError;
VALUE __rubex_rb_cls_RcsvParseError;
VALUE __rubex_rb_cls_Rcsv;
static VALUE __rubex_rb_f_Rcsv_parse (int argc,VALUE* argv,VALUE __rubex_arg_self);
static VALUE __rubex_c_f_Rcsv_validate_filter_row (VALUE __rubex_arg_row,VALUE __rubex_arg_self);
static void __rubex_c_f_Rcsv_end_of_field_callback (void* __rubex_arg_field,size_t __rubex_arg_field_size,void* __rubex_arg_data,VALUE __rubex_arg_self);
static void __rubex_c_f_Rcsv_raise_with_location (size_t __rubex_arg_current_row,size_t __rubex_arg_current_col,char* __rubex_arg_string,VALUE __rubex_arg_self);
static void __rubex_c_f_Rcsv_end_of_line_callback (int __rubex_arg_last_char,void* __rubex_arg_data,VALUE __rubex_arg_self);
static VALUE __rubex_c_f_Rcsv_ENCODED_STR_NEW (char* __rubex_arg_string,int __rubex_arg_length,int __rubex_arg_enc_index,VALUE __rubex_arg_self);
static void __rubex_c_f_Rcsv_free_all_memory (struct csv_parser* __rubex_arg_p_cp,__rubex_t_Object_rcsv_metadata* __rubex_arg_p_meta,VALUE __rubex_arg_self);
static void __rubex_c_f_Rcsv_setup_rcsv_metadata_defaults (__rubex_t_Object_rcsv_metadata* __rubex_arg_p_meta,VALUE __rubex_arg_self);

VALUE __rubex_char2rubystr(char ch);
VALUE __rubex_char2rubystr(char ch)
{
  char s[2];
  s[0] = ch;
  s[1] = '\0';
  return rb_str_new2(s);
}


static VALUE __rubex_c_f_Rcsv_validate_filter_row (VALUE __rubex_arg_row,VALUE __rubex_arg_self)
{
  size_t __rubex_v_j;
  int __rubex_v_r_size;
  int __rubex_v_type;
  VALUE __rubex_temp_1;
  if (RTEST(( rb_funcall(__rubex_arg_row, rb_intern("==") , 1, Qnil) ))) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:80 */
    return Qnil;

  }

  else if (RTEST(rb_funcall(__rubex_arg_row, rb_intern("is_a?"), 1 ,rb_cArray))) 
  {

    __rubex_v_r_size = NUM2INT(rb_funcall(__rubex_arg_row, rb_intern("size"), 0, NULL));


    for (__rubex_v_j = 0; __rubex_v_j < __rubex_v_r_size; __rubex_v_j++)
    {

      /* Rubex file location: ext/rcsv/rcsv.rubex:86 */
      __rubex_temp_1 = rb_funcall(__rubex_arg_row, rb_intern("[]"), 1,       rb_funcall(__rubex_arg_self, rb_intern("i"), 0, NULL));
      __rubex_v_type = TYPE(__rubex_temp_1);
      __rubex_temp_1 = 0;
      __rubex_temp_1 = 0;
      if (( ( ( ( ( ( ( __rubex_v_type == T_NIL ) || ( __rubex_v_type == T_TRUE ) ) || ( __rubex_v_type == T_FALSE ) ) || ( __rubex_v_type == T_FLOAT ) ) || ( __rubex_v_type == T_FLOAT ) ) || ( __rubex_v_type == T_FIXNUM ) ) || ( __rubex_v_type == T_STRING ) )) 
      {

        /* Rubex file location: ext/rcsv/rcsv.rubex:89 */
        break;

      }

      else
      {
        __rubex_temp_1 = rb_str_new2("Wrong type passed.");
        rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
        __rubex_temp_1 = 0;

      }

    }



    /* Rubex file location: ext/rcsv/rcsv.rubex:94 */
    return __rubex_arg_row;

  }

  else
  {
    __rubex_temp_1 = rb_str_new2("Wrong type passed.");
    rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
    __rubex_temp_1 = 0;

  }

}

static void __rubex_c_f_Rcsv_end_of_field_callback (void* __rubex_arg_field,size_t __rubex_arg_field_size,void* __rubex_arg_data,VALUE __rubex_arg_self)
{
  char* __rubex_ptr_field_str;
  __rubex_t_Object_rcsv_metadata* __rubex_ptr_meta_p;
  __rubex_t_Object_rcsv_metadata __rubex_v_meta;
  char __rubex_v_row_conversion;
  VALUE __rubex_v_parsed_field;
  VALUE __rubex_temp_1;
  __rubex_ptr_field_str = (char*)__rubex_arg_field;
  __rubex_ptr_meta_p = (__rubex_t_Object_rcsv_metadata*)__rubex_arg_data;
  __rubex_v_meta = __rubex_ptr_meta_p[0];
  __rubex_v_row_conversion = 0;
  if (( __rubex_v_meta.__rubex_v_current_row < __rubex_v_meta.__rubex_v_offset_rows )) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:113 */
    __rubex_ptr_meta_p[0].__rubex_v_skip_current_row = 1;


    /* Rubex file location: ext/rcsv/rcsv.rubex:114 */
    return ;

  }


  /* Rubex file location: ext/rcsv/rcsv.rubex:117 */
  __rubex_v_parsed_field = __rubex_c_f_Rcsv_ENCODED_STR_NEW(__rubex_ptr_field_str,__rubex_arg_field_size,__rubex_v_meta.__rubex_v_encoding_index,__rubex_arg_self);
  if (RTEST(( __rubex_INT2BOOL(RTEST(( __rubex_INT2BOOL(RTEST(__rubex_INT2BOOL(( ( __rubex_v_meta.__rubex_ptr_only_rows != NULL ) && ( __rubex_v_meta.__rubex_v_current_col < __rubex_v_meta.__rubex_v_num_only_rows ) ))) && RTEST(( rb_funcall(__rubex_v_meta.__rubex_ptr_only_rows[__rubex_v_meta.__rubex_v_current_col], rb_intern("!=") , 1, Qnil) ))) )) && RTEST(!rb_ary_includes(__rubex_v_meta.__rubex_ptr_only_rows[__rubex_v_meta.__rubex_v_current_col],__rubex_v_parsed_field))) ))) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:121 */
    __rubex_ptr_meta_p[0].__rubex_v_skip_current_row = 1;


    /* Rubex file location: ext/rcsv/rcsv.rubex:122 */
    return ;

  }

  if (RTEST(( __rubex_INT2BOOL(RTEST(( __rubex_INT2BOOL(RTEST(__rubex_INT2BOOL(( ( __rubex_v_meta.__rubex_ptr_except_rows != NULL ) && ( __rubex_v_meta.__rubex_v_current_col < __rubex_v_meta.__rubex_v_num_except_rows ) ))) && RTEST(( rb_funcall(__rubex_v_meta.__rubex_ptr_except_rows[__rubex_v_meta.__rubex_v_current_col], rb_intern("!=") , 1, Qnil) ))) )) && RTEST(rb_ary_includes(__rubex_v_meta.__rubex_ptr_except_rows[__rubex_v_meta.__rubex_v_current_col],__rubex_v_parsed_field))) ))) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:126 */
    __rubex_v_meta.__rubex_v_skip_current_row = 1;


    /* Rubex file location: ext/rcsv/rcsv.rubex:127 */
    return ;

  }

  if (__rubex_v_meta.__rubex_v_row_as_hash) 
  {
    if (( __rubex_v_meta.__rubex_v_current_col >= __rubex_v_meta.__rubex_v_num_columns )) 
    {

      /* Rubex file location: ext/rcsv/rcsv.rubex:133 */
      __rubex_c_f_Rcsv_raise_with_location(__rubex_v_meta.__rubex_v_current_row,__rubex_v_meta.__rubex_v_current_col,__rubex_ptr_field_str,__rubex_arg_self);

    }

    else
    {

      /* Rubex file location: ext/rcsv/rcsv.rubex:135 */
      __rubex_temp_1 = rb_funcall(__rubex_ptr_meta_p[0].__rubex_v_last_entry, rb_intern("[]"), 1, __rubex_v_meta.__rubex_ptr_column_names[__rubex_v_meta.__rubex_v_current_col]);
      __rubex_temp_1 = __rubex_v_parsed_field;

    }


  }

  else
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:138 */
    rb_funcall(__rubex_ptr_meta_p[0].__rubex_v_last_entry, rb_intern("push"), 1 ,__rubex_v_parsed_field);

  }


  /* Rubex file location: ext/rcsv/rcsv.rubex:142 */
  __rubex_ptr_meta_p[0].__rubex_v_current_col = ( __rubex_ptr_meta_p[0].__rubex_v_current_col + 1 );

  /* Rubex file location: ext/rcsv/rcsv.rubex:143 */
  return ;
}

static void __rubex_c_f_Rcsv_raise_with_location (size_t __rubex_arg_current_row,size_t __rubex_arg_current_col,char* __rubex_arg_string,VALUE __rubex_arg_self)
{
}

static void __rubex_c_f_Rcsv_end_of_line_callback (int __rubex_arg_last_char,void* __rubex_arg_data,VALUE __rubex_arg_self)
{
  __rubex_t_Object_rcsv_metadata* __rubex_ptr_meta_p;
  __rubex_t_Object_rcsv_metadata __rubex_v_meta;
  VALUE __rubex_temp_1;
  __rubex_ptr_meta_p = (__rubex_t_Object_rcsv_metadata*)__rubex_arg_data;
  __rubex_v_meta = __rubex_ptr_meta_p[0];
  if (__rubex_v_meta.__rubex_v_skip_current_row) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:155 */
    __rubex_v_meta.__rubex_v_skip_current_row = 0;

  }

  else
  {
    if (rb_block_given_p()) 
    {
      rb_yield_values(1,       __rubex_v_meta.__rubex_v_last_entry      );

    }

    else
    {

      /* Rubex file location: ext/rcsv/rcsv.rubex:160 */
      rb_funcall(__rubex_ptr_meta_p[0].__rubex_v_result, rb_intern("push"), 1 ,__rubex_v_meta.__rubex_v_last_entry);

    }


  }

  if (( __rubex_arg_last_char != -1 )) 
  {
    if (__rubex_v_meta.__rubex_v_row_as_hash) 
    {

      /* Rubex file location: ext/rcsv/rcsv.rubex:167 */
      __rubex_temp_1 = rb_hash_new();
      __rubex_v_meta.__rubex_v_last_entry = __rubex_temp_1;
      __rubex_temp_1 = 0;

    }

    else
    {

      /* Rubex file location: ext/rcsv/rcsv.rubex:169 */
      __rubex_temp_1 = rb_ary_new2(0);
      __rubex_ptr_meta_p[0].__rubex_v_last_entry = __rubex_temp_1;
      __rubex_temp_1 = 0;

    }


  }


  /* Rubex file location: ext/rcsv/rcsv.rubex:174 */
  __rubex_v_meta.__rubex_v_current_col = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:177 */
  __rubex_v_meta.__rubex_v_current_row = ( __rubex_v_meta.__rubex_v_current_row + 1 );
}

static VALUE __rubex_c_f_Rcsv_ENCODED_STR_NEW (char* __rubex_arg_string,int __rubex_arg_length,int __rubex_arg_enc_index,VALUE __rubex_arg_self)
{
  VALUE __rubex_v__string;

  /* Rubex file location: ext/rcsv/rcsv.rubex:181 */
  __rubex_v__string = rb_str_new(__rubex_arg_string,__rubex_arg_length);
  if (( __rubex_arg_enc_index != -1 )) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:183 */
    rb_enc_associate_index(__rubex_v__string,__rubex_arg_enc_index);

  }


  /* Rubex file location: ext/rcsv/rcsv.rubex:185 */
  return __rubex_v__string;
}

static void __rubex_c_f_Rcsv_free_all_memory (struct csv_parser* __rubex_arg_p_cp,__rubex_t_Object_rcsv_metadata* __rubex_arg_p_meta,VALUE __rubex_arg_self)
{
  if (__rubex_arg_p_cp) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:190 */
    csv_free(__rubex_arg_p_cp);

  }

}

static void __rubex_c_f_Rcsv_setup_rcsv_metadata_defaults (__rubex_t_Object_rcsv_metadata* __rubex_arg_p_meta,VALUE __rubex_arg_self)
{
  VALUE __rubex_temp_1;

  /* Rubex file location: ext/rcsv/rcsv.rubex:195 */
  __rubex_arg_p_meta[0].__rubex_v_row_as_hash = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:196 */
  __rubex_arg_p_meta[0].__rubex_v_empty_field_is_nil = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:197 */
  __rubex_arg_p_meta[0].__rubex_v_skip_current_row = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:198 */
  __rubex_arg_p_meta[0].__rubex_v_encoding_index = -1;

  /* Rubex file location: ext/rcsv/rcsv.rubex:199 */
  __rubex_arg_p_meta[0].__rubex_v_num_columns = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:200 */
  __rubex_arg_p_meta[0].__rubex_v_current_col = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:201 */
  __rubex_arg_p_meta[0].__rubex_v_current_row = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:202 */
  __rubex_arg_p_meta[0].__rubex_v_offset_rows = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:203 */
  __rubex_arg_p_meta[0].__rubex_v_num_only_rows = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:204 */
  __rubex_arg_p_meta[0].__rubex_v_num_except_rows = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:205 */
  __rubex_arg_p_meta[0].__rubex_v_num_row_defaults = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:206 */
  __rubex_arg_p_meta[0].__rubex_v_num_row_conversions = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:207 */
  __rubex_arg_p_meta[0].__rubex_ptr_only_rows = NULL;

  /* Rubex file location: ext/rcsv/rcsv.rubex:208 */
  __rubex_arg_p_meta[0].__rubex_ptr_except_rows = NULL;

  /* Rubex file location: ext/rcsv/rcsv.rubex:209 */
  __rubex_arg_p_meta[0].__rubex_ptr_row_defaults = NULL;

  /* Rubex file location: ext/rcsv/rcsv.rubex:210 */
  __rubex_arg_p_meta[0].__rubex_ptr_row_conversions = NULL;

  /* Rubex file location: ext/rcsv/rcsv.rubex:211 */
  __rubex_arg_p_meta[0].__rubex_ptr_column_names = NULL;

  /* Rubex file location: ext/rcsv/rcsv.rubex:212 */
  __rubex_temp_1 = rb_ary_new2(0);
  __rubex_arg_p_meta[0].__rubex_v_result = __rubex_temp_1;
  __rubex_temp_1 = 0;
}

static VALUE __rubex_rb_f_Rcsv_parse (int argc,VALUE* argv,VALUE __rubex_arg_self)
{
  VALUE __rubex_arg_file_name;
  VALUE __rubex_arg_opts;
  __rubex_t_Object_rcsv_metadata __rubex_v_meta;
  VALUE __rubex_v_csvio;
  VALUE __rubex_v_options;
  VALUE __rubex_v_option;
  struct csv_parser __rubex_v_cp;
  unsigned char __rubex_v_csv_options;
  int __rubex_v_csv_string_len;
  int __rubex_v_i;
  char* __rubex_ptr_csv_string;
  int __rubex_v_error;
  VALUE __rubex_v_ensure_container;
  VALUE __rubex_v_buffer_size;
  VALUE __rubex_v_only_row;
  VALUE __rubex_v_row_conversions;
  VALUE __rubex_v_column_names;
  VALUE __rubex_v_csvstr;
  VALUE __rubex_temp_1;
  if (argc < 2)
  {
    rb_raise(rb_eArgError, "Need 2 args, not %d", argc);
  }

  __rubex_arg_file_name=argv[0];
  __rubex_arg_opts=argv[1];

  /* Rubex file location: ext/rcsv/rcsv.rubex:219 */
  __rubex_temp_1 = rb_ary_new2(0);
  __rubex_v_ensure_container = __rubex_temp_1;
  __rubex_temp_1 = 0;
  __rubex_temp_1 = 0;
  __rubex_v_csv_options = ( CSV_STRICT_FINI | CSV_APPEND_NULL );

  /* Rubex file location: ext/rcsv/rcsv.rubex:223 */
  __rubex_c_f_Rcsv_setup_rcsv_metadata_defaults(&__rubex_v_meta,__rubex_arg_self);

  /* Rubex file location: ext/rcsv/rcsv.rubex:224 */
  __rubex_v_csvio = rb_funcall(rb_const_get(CLASS_OF(__rubex_arg_self), rb_intern("StringIO")), rb_intern("new"), 1 ,__rubex_arg_file_name);
  __rubex_temp_1 = rb_funcall(__rubex_arg_opts, rb_intern("[]"), 1,   ID2SYM(rb_intern("nostrict")));
  if (RTEST(rb_funcall(__rubex_temp_1, rb_intern("!"), 0))) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:227 */
    __rubex_v_csv_options = ( __rubex_v_csv_options | CSV_STRICT );

  }


  /* Rubex file location: ext/rcsv/rcsv.rubex:230 */
  __rubex_temp_1 = rb_funcall(__rubex_arg_opts, rb_intern("[]"), 1,   ID2SYM(rb_intern("parse_empty_fields_as")));
  __rubex_v_option = __rubex_temp_1;
  __rubex_temp_1 = 0;
  __rubex_temp_1 = 0;
  if (RTEST(( __rubex_INT2BOOL(RTEST(( rb_funcall(__rubex_v_option, rb_intern("==") , 1, Qnil) )) || RTEST(( rb_funcall(__rubex_v_option, rb_intern("==") , 1, ID2SYM(rb_intern("nil_or_string"))) ))) ))) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:233 */
    __rubex_v_csv_options = ( __rubex_v_csv_options | CSV_EMPTY_IS_NULL );

  }

  else if (RTEST(rb_funcall(__rubex_v_option, rb_intern("nil?"), 0, NULL))) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:235 */
    __rubex_v_meta.__rubex_v_empty_field_is_nil = 1;

  }

  else if (RTEST(( rb_funcall(__rubex_v_option, rb_intern("==") , 1, ID2SYM(rb_intern("string"))) ))) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:237 */
    __rubex_v_meta.__rubex_v_empty_field_is_nil = 0;

  }

  else
  {
    __rubex_temp_1 = rb_str_new2("The only valid options for :parse_empty_fields_as are :nil, :string and :nil_or_string.");
    rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
    __rubex_temp_1 = 0;

  }

  if (( csv_init(&__rubex_v_cp,__rubex_v_csv_options) == -1 )) 
  {
    __rubex_temp_1 = rb_str_new2("Failed to initialize libcsv.");
    rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
    __rubex_temp_1 = 0;

  }


  /* Rubex file location: ext/rcsv/rcsv.rubex:246 */
  __rubex_temp_1 = rb_funcall(__rubex_arg_opts, rb_intern("[]"), 1,   ID2SYM(rb_intern("buffer_size")));
  __rubex_v_buffer_size = __rubex_temp_1;
  __rubex_temp_1 = 0;
  __rubex_temp_1 = 0;
  __rubex_temp_1 = rb_funcall(__rubex_arg_opts, rb_intern("[]"), 1,   ID2SYM(rb_intern("row_as_hash")));
  if (RTEST(__rubex_temp_1)) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:247 */
    __rubex_v_meta.__rubex_v_row_as_hash = 1;

  }

  __rubex_temp_1 = 0;
  __rubex_temp_1 = rb_funcall(__rubex_arg_opts, rb_intern("[]"), 1,   ID2SYM(rb_intern("col_sep")));
  if (RTEST(__rubex_temp_1)) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:249 */
    csv_set_delim(&__rubex_v_cp,(unsigned char)NUM2INT(rb_funcall(__rubex_arg_self, rb_intern("col_sep"), 0, NULL)));

  }

  __rubex_temp_1 = 0;
  __rubex_temp_1 = rb_funcall(__rubex_arg_opts, rb_intern("[]"), 1,   ID2SYM(rb_intern("quote_char")));
  if (RTEST(__rubex_temp_1)) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:250 */
    csv_set_quote(&__rubex_v_cp,(unsigned char)NUM2INT(rb_funcall(__rubex_arg_self, rb_intern("quote_char"), 0, NULL)));

  }

  __rubex_temp_1 = 0;
  __rubex_temp_1 = rb_funcall(__rubex_arg_opts, rb_intern("[]"), 1,   ID2SYM(rb_intern("offset_rows")));
  if (RTEST(__rubex_temp_1)) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:252 */
    __rubex_temp_1 = rb_funcall(__rubex_arg_opts, rb_intern("[]"), 1,     ID2SYM(rb_intern("offset_rows")));
    __rubex_v_meta.__rubex_v_offset_rows = NUM2ULONG(__rubex_temp_1);
    __rubex_temp_1 = 0;

  }

  __rubex_temp_1 = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:255 */
  __rubex_temp_1 = rb_funcall(__rubex_arg_opts, rb_intern("[]"), 1,   ID2SYM(rb_intern("output_encoding")));
  __rubex_v_option = __rubex_temp_1;
  __rubex_temp_1 = 0;
  __rubex_temp_1 = 0;
  if (RTEST(( rb_funcall(__rubex_v_option, rb_intern("!=") , 1, Qnil) ))) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:256 */
    __rubex_v_meta.__rubex_v_encoding_index = rb_enc_find_index((char*)__rubex_v_option);

  }


  /* Rubex file location: ext/rcsv/rcsv.rubex:260 */
  __rubex_temp_1 = rb_funcall(__rubex_arg_opts, rb_intern("[]"), 1,   ID2SYM(rb_intern("only_rows")));
  __rubex_v_option = __rubex_temp_1;
  __rubex_temp_1 = 0;
  __rubex_temp_1 = 0;
  if (RTEST(__rubex_v_option)) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:262 */
    __rubex_v_meta.__rubex_v_num_only_rows = NUM2ULONG(rb_funcall(__rubex_v_option, rb_intern("size"), 0, NULL));


    /* Rubex file location: ext/rcsv/rcsv.rubex:263 */
    __rubex_v_meta.__rubex_ptr_only_rows = (VALUE*)xmalloc(( __rubex_v_meta.__rubex_v_num_only_rows * sizeof(VALUE) ));

    __rubex_v_i = 0;

    for (__rubex_v_i = 0; __rubex_v_i < __rubex_v_meta.__rubex_v_num_only_rows; __rubex_v_i++)
    {

      /* Rubex file location: ext/rcsv/rcsv.rubex:268 */
      __rubex_temp_1 = rb_funcall(__rubex_v_option, rb_intern("[]"), 1,       INT2NUM(__rubex_v_i));
      __rubex_v_only_row = __rubex_temp_1;
      __rubex_temp_1 = 0;
      __rubex_temp_1 = 0;

      /* Rubex file location: ext/rcsv/rcsv.rubex:269 */
      __rubex_v_meta.__rubex_ptr_only_rows[__rubex_v_i] = __rubex_c_f_Rcsv_validate_filter_row(__rubex_v_only_row,__rubex_arg_self);
    }


  }


  /* Rubex file location: ext/rcsv/rcsv.rubex:278 */
  __rubex_temp_1 = rb_funcall(__rubex_arg_opts, rb_intern("[]"), 1,   ID2SYM(rb_intern("row_conversions")));
  __rubex_v_row_conversions = __rubex_temp_1;
  __rubex_temp_1 = 0;
  __rubex_temp_1 = 0;
  if (RTEST(__rubex_v_row_conversions)) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:280 */
    __rubex_v_meta.__rubex_v_num_row_conversions = NUM2ULONG(rb_funcall(__rubex_v_row_conversions, rb_intern("size"), 0, NULL));


    /* Rubex file location: ext/rcsv/rcsv.rubex:281 */
    __rubex_v_meta.__rubex_ptr_row_conversions = StringValueCStr(__rubex_v_row_conversions);

  }

  if (__rubex_v_meta.__rubex_v_row_as_hash) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:285 */
    __rubex_temp_1 = rb_funcall(__rubex_arg_opts, rb_intern("[]"), 1,     ID2SYM(rb_intern("column_names")));
    __rubex_v_column_names = __rubex_temp_1;
    __rubex_temp_1 = 0;
    __rubex_temp_1 = 0;

    if (RTEST(rb_funcall(__rubex_v_column_names, rb_intern("nil?"), 0, NULL))) 
    {
    }

    else
    {

      /* Rubex file location: ext/rcsv/rcsv.rubex:290 */
      __rubex_temp_1 = rb_hash_new();
      __rubex_v_meta.__rubex_v_last_entry = __rubex_temp_1;
      __rubex_temp_1 = 0;


      /* Rubex file location: ext/rcsv/rcsv.rubex:291 */
      __rubex_v_meta.__rubex_v_num_columns = NUM2ULONG(rb_funcall(__rubex_v_column_names, rb_intern("size"), 0, NULL));


      /* Rubex file location: ext/rcsv/rcsv.rubex:292 */
      __rubex_v_meta.__rubex_ptr_column_names = __rubex_v_column_names;

    }


  }

  else
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:295 */
    __rubex_temp_1 = rb_ary_new2(0);
    __rubex_v_meta.__rubex_v_last_entry = __rubex_temp_1;
    __rubex_temp_1 = 0;

  }

  while (Qtrue)
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:299 */
    __rubex_v_csvstr = rb_funcall(__rubex_v_csvio, rb_intern("read"), 0, NULL);
    if (RTEST(( __rubex_INT2BOOL(RTEST(rb_funcall(__rubex_v_csvstr, rb_intern("nil?"), 0, NULL)) || RTEST(( rb_funcall(rb_funcall(__rubex_v_csvstr, rb_intern("size"), 0, NULL), rb_intern("==") , 1, INT2NUM(0)) ))) ))) 
    {

      /* Rubex file location: ext/rcsv/rcsv.rubex:302 */
      break;

    }

    __rubex_ptr_csv_string = StringValueCStr(__rubex_v_csvstr);

    /* Rubex file location: ext/rcsv/rcsv.rubex:306 */
    __rubex_v_csv_string_len = NUM2INT(rb_funcall(__rubex_v_csvstr, rb_intern("size"), 0, NULL));
    if (( __rubex_v_csv_string_len != csv_parse(&__rubex_v_cp,__rubex_ptr_csv_string,__rubex_v_csv_string_len,&__rubex_c_f_Rcsv_end_of_field_callback,&__rubex_c_f_Rcsv_end_of_line_callback,&__rubex_v_meta) )) 
    {
      __rubex_v_error = csv_error(&__rubex_v_cp);

      if (( __rubex_v_error == CSV_EPARSE )) 
      {
        __rubex_temp_1 = rb_str_new2("Error when parsing malformed data.");
        rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
        __rubex_temp_1 = 0;

      }

      else if (( __rubex_v_error == CSV_ENOMEM )) 
      {
        __rubex_temp_1 = rb_str_new2("No memory.");
        rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
        __rubex_temp_1 = 0;

      }

      else if (( __rubex_v_error == CSV_ETOOBIG )) 
      {
        __rubex_temp_1 = rb_str_new2("Field data data is too large.");
        rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
        __rubex_temp_1 = 0;

      }

      else if (( __rubex_v_error == CSV_EINVALID )) 
      {
        __rubex_temp_1 = rb_str_new2("#{csv_strerror(error)}");
        rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
        __rubex_temp_1 = 0;

      }

      else
      {
        __rubex_temp_1 = rb_str_new2("Something went wrong.");
        rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
        __rubex_temp_1 = 0;

      }


    }

  }


  /* Rubex file location: ext/rcsv/rcsv.rubex:325 */
  csv_fini(&__rubex_v_cp,&__rubex_c_f_Rcsv_end_of_field_callback,&__rubex_c_f_Rcsv_end_of_line_callback,&__rubex_v_meta);

  /* Rubex file location: ext/rcsv/rcsv.rubex:326 */
  __rubex_c_f_Rcsv_free_all_memory(&__rubex_v_cp,&__rubex_v_meta,__rubex_arg_self);

  /* Rubex file location: ext/rcsv/rcsv.rubex:327 */
  return __rubex_v_meta.__rubex_v_result;
}


void Init_rcsv ();
void Init_rcsv ()
{
  VALUE __rubex_rb_cls_RcsvParseError;
  VALUE __rubex_rb_cls_Rcsv;

  __rubex_rb_cls_RcsvParseError = rb_define_class("RcsvParseError", rb_eStandardError);
  __rubex_rb_cls_Rcsv = rb_define_class("Rcsv", rb_cObject);

  rb_define_singleton_method(__rubex_rb_cls_Rcsv ,"parse", __rubex_rb_f_Rcsv_parse, -1);
}

