/* C extension for rcsv.
This file in generated by Rubex::Compiler. Do not change!
File generation time: 2017-08-28 23:47:06 +0530.*/

#include <ruby.h>
#include <stdint.h>
#include <stdbool.h>
#include <ruby.h>
#include <ruby/encoding.h>
#include <stdlib.h>
#include "csv.h"

#define __rubex_INT2BOOL(arg) (arg ? Qtrue : Qfalse)



typedef struct rcsv_metadata
{
  int __rubex_v_skip_current_row;
  size_t __rubex_v_current_col;
  size_t __rubex_v_current_row;
  VALUE __rubex_v_last_entry;
  VALUE __rubex_v_result;
} __rubex_t_Object_rcsv_metadata;



VALUE rb_cObject;
VALUE rb_eStandardError;
VALUE __rubex_rb_cls_RcsvParseError;
VALUE __rubex_rb_cls_Rcsv;
static VALUE global_begin_block_Rcsv_parse_1__rubex_arg_dummy;
static VALUE global_begin_block_Rcsv_parse_1__rubex_v_csvstr;
static VALUE global_begin_block_Rcsv_parse_1__rubex_v_csvio;
static char* global_begin_block_Rcsv_parse_1__rubex_ptr_csv_string;
static int global_begin_block_Rcsv_parse_1__rubex_v_csv_string_len;
static struct csv_parser global_begin_block_Rcsv_parse_1__rubex_v_cp;
static __rubex_t_Object_rcsv_metadata global_begin_block_Rcsv_parse_1__rubex_v_meta;
static int global_begin_block_Rcsv_parse_1__rubex_v_error;
static VALUE __rubex_rb_f_Rcsv_parse (int argc,VALUE* argv,VALUE __rubex_arg_self);
static void __rubex_c_f_Rcsv_end_of_field_callback (void* __rubex_arg_field,size_t __rubex_arg_field_size,void* __rubex_arg_data,VALUE __rubex_arg_self);
static void __rubex_c_f_Rcsv_end_of_line_callback (int __rubex_arg_last_char,void* __rubex_arg_data,VALUE __rubex_arg_self);
static VALUE __rubex_c_f_Rcsv_ENCODED_STR_NEW (char* __rubex_arg_string,int __rubex_arg_length,VALUE __rubex_arg_self);
static void __rubex_c_f_Rcsv_setup_rcsv_metadata_defaults (__rubex_t_Object_rcsv_metadata* __rubex_arg_p_meta,VALUE __rubex_arg_self);
static VALUE __rubex_c_f_begin_block_Rcsv_parse_1 (VALUE global_begin_block_Rcsv_parse_1__rubex_arg_dummy);

VALUE __rubex_char2rubystr(char ch);
VALUE __rubex_char2rubystr(char ch)
{
  char s[2];
  s[0] = ch;
  s[1] = '\0';
  return rb_str_new2(s);
}


static VALUE __rubex_c_f_begin_block_Rcsv_parse_1 (VALUE global_begin_block_Rcsv_parse_1__rubex_arg_dummy)
{
  VALUE __rubex_v_ensure_container;
  VALUE __rubex_temp_1;
  while (Qtrue)
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:93 */
    global_begin_block_Rcsv_parse_1__rubex_v_csvstr = rb_funcall(global_begin_block_Rcsv_parse_1__rubex_v_csvio, rb_intern("read"), 0, NULL);
    if (RTEST(( __rubex_INT2BOOL(RTEST(rb_funcall(global_begin_block_Rcsv_parse_1__rubex_v_csvstr, rb_intern("nil?"), 0, NULL)) || RTEST(( rb_funcall(rb_funcall(global_begin_block_Rcsv_parse_1__rubex_v_csvstr, rb_intern("size"), 0, NULL), rb_intern("==") , 1, INT2NUM(0)) ))) ))) 
    {

      /* Rubex file location: ext/rcsv/rcsv.rubex:95 */
      break;

    }

    global_begin_block_Rcsv_parse_1__rubex_ptr_csv_string = StringValueCStr(global_begin_block_Rcsv_parse_1__rubex_v_csvstr);

    /* Rubex file location: ext/rcsv/rcsv.rubex:98 */
    global_begin_block_Rcsv_parse_1__rubex_v_csv_string_len = NUM2INT(rb_funcall(global_begin_block_Rcsv_parse_1__rubex_v_csvstr, rb_intern("size"), 0, NULL));
    if (( global_begin_block_Rcsv_parse_1__rubex_v_csv_string_len != csv_parse(&global_begin_block_Rcsv_parse_1__rubex_v_cp,global_begin_block_Rcsv_parse_1__rubex_ptr_csv_string,global_begin_block_Rcsv_parse_1__rubex_v_csv_string_len,&__rubex_c_f_Rcsv_end_of_field_callback,&__rubex_c_f_Rcsv_end_of_line_callback,&global_begin_block_Rcsv_parse_1__rubex_v_meta) )) 
    {
      global_begin_block_Rcsv_parse_1__rubex_v_error = csv_error(&global_begin_block_Rcsv_parse_1__rubex_v_cp);

      if (( global_begin_block_Rcsv_parse_1__rubex_v_error == CSV_EPARSE )) 
      {
        __rubex_temp_1 = rb_str_new2("Error when parsing malformed data.");
        rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
        __rubex_temp_1 = 0;

      }

      else if (( global_begin_block_Rcsv_parse_1__rubex_v_error == CSV_ENOMEM )) 
      {
        __rubex_temp_1 = rb_str_new2("No memory.");
        rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
        __rubex_temp_1 = 0;

      }

      else if (( global_begin_block_Rcsv_parse_1__rubex_v_error == CSV_ETOOBIG )) 
      {
        __rubex_temp_1 = rb_str_new2("Field data data is too large.");
        rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
        __rubex_temp_1 = 0;

      }

      else if (( global_begin_block_Rcsv_parse_1__rubex_v_error == CSV_EINVALID )) 
      {
        rb_raise(__rubex_rb_cls_RcsvParseError,"");

      }

      else
      {
        __rubex_temp_1 = rb_str_new2("Something went wrong.");
        rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
        __rubex_temp_1 = 0;

      }


    }

  }


  /* Rubex file location: ext/rcsv/rcsv.rubex:117 */
  csv_fini(&global_begin_block_Rcsv_parse_1__rubex_v_cp,&__rubex_c_f_Rcsv_end_of_field_callback,&__rubex_c_f_Rcsv_end_of_line_callback,&global_begin_block_Rcsv_parse_1__rubex_v_meta);
}

static void __rubex_c_f_Rcsv_end_of_field_callback (void* __rubex_arg_field,size_t __rubex_arg_field_size,void* __rubex_arg_data,VALUE __rubex_arg_self)
{
  char* __rubex_ptr_field_str;
  __rubex_t_Object_rcsv_metadata* __rubex_ptr_meta_p;
  __rubex_t_Object_rcsv_metadata __rubex_v_meta;
  char __rubex_v_row_conversion;
  VALUE __rubex_v_parsed_field;
  __rubex_ptr_field_str = (char*)__rubex_arg_field;
  __rubex_ptr_meta_p = (__rubex_t_Object_rcsv_metadata*)__rubex_arg_data;
  __rubex_v_meta = __rubex_ptr_meta_p[0];
  __rubex_v_row_conversion = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:48 */
  __rubex_v_parsed_field = __rubex_c_f_Rcsv_ENCODED_STR_NEW(__rubex_ptr_field_str,__rubex_arg_field_size,__rubex_arg_self);

  /* Rubex file location: ext/rcsv/rcsv.rubex:50 */
  rb_funcall(__rubex_ptr_meta_p[0].__rubex_v_last_entry, rb_intern("push"), 1 ,__rubex_v_parsed_field);

  /* Rubex file location: ext/rcsv/rcsv.rubex:51 */
  __rubex_ptr_meta_p[0].__rubex_v_current_col = ( __rubex_ptr_meta_p[0].__rubex_v_current_col + 1 );

  /* Rubex file location: ext/rcsv/rcsv.rubex:52 */
  return ;
}

static void __rubex_c_f_Rcsv_end_of_line_callback (int __rubex_arg_last_char,void* __rubex_arg_data,VALUE __rubex_arg_self)
{
  __rubex_t_Object_rcsv_metadata* __rubex_ptr_meta;
  VALUE __rubex_temp_1;
  __rubex_ptr_meta = (__rubex_t_Object_rcsv_metadata*)__rubex_arg_data;

  /* Rubex file location: ext/rcsv/rcsv.rubex:58 */
  rb_funcall(__rubex_ptr_meta->__rubex_v_result, rb_intern("push"), 1 ,__rubex_ptr_meta->__rubex_v_last_entry);
  if (( __rubex_arg_last_char != -1 )) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:59 */
    __rubex_temp_1 = rb_ary_new2(0);
    __rubex_ptr_meta->__rubex_v_last_entry = __rubex_temp_1;
    __rubex_temp_1 = 0;

  }


  /* Rubex file location: ext/rcsv/rcsv.rubex:60 */
  __rubex_ptr_meta->__rubex_v_current_col = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:61 */
  __rubex_ptr_meta->__rubex_v_current_row = ( __rubex_ptr_meta->__rubex_v_current_row + 1 );
}

static VALUE __rubex_c_f_Rcsv_ENCODED_STR_NEW (char* __rubex_arg_string,int __rubex_arg_length,VALUE __rubex_arg_self)
{

  /* Rubex file location: ext/rcsv/rcsv.rubex:65 */
  return rb_str_new(__rubex_arg_string,__rubex_arg_length);
}

static void __rubex_c_f_Rcsv_setup_rcsv_metadata_defaults (__rubex_t_Object_rcsv_metadata* __rubex_arg_p_meta,VALUE __rubex_arg_self)
{
  VALUE __rubex_temp_1;

  /* Rubex file location: ext/rcsv/rcsv.rubex:69 */
  __rubex_arg_p_meta->__rubex_v_skip_current_row = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:70 */
  __rubex_arg_p_meta->__rubex_v_current_col = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:71 */
  __rubex_arg_p_meta->__rubex_v_current_row = 0;

  /* Rubex file location: ext/rcsv/rcsv.rubex:72 */
  __rubex_temp_1 = rb_ary_new2(0);
  __rubex_arg_p_meta->__rubex_v_result = __rubex_temp_1;
  __rubex_temp_1 = 0;
}

static VALUE __rubex_rb_f_Rcsv_parse (int argc,VALUE* argv,VALUE __rubex_arg_self)
{
  VALUE __rubex_arg_file_name;
  VALUE __rubex_arg_opts;
  VALUE __rubex_v_options;
  VALUE __rubex_v_option;
  unsigned char __rubex_v_csv_options;
  int __rubex_v_begin_block_1_state;
  VALUE __rubex_v_begin_block_1_exec;
  int __rubex_v_begin_block_1_unhandled_error;
  VALUE __rubex_v_ensure_container;
  VALUE __rubex_temp_1;
  if (argc < 2)
  {
    rb_raise(rb_eArgError, "Need 2 args, not %d", argc);
  }

  __rubex_arg_file_name=argv[0];
  __rubex_arg_opts=argv[1];

  /* Rubex file location: ext/rcsv/rcsv.rubex:79 */
  __rubex_temp_1 = rb_ary_new2(0);
  __rubex_v_ensure_container = __rubex_temp_1;
  __rubex_temp_1 = 0;
  __rubex_temp_1 = 0;
  __rubex_v_csv_options = ( CSV_STRICT_FINI | CSV_APPEND_NULL );

  /* Rubex file location: ext/rcsv/rcsv.rubex:83 */
  __rubex_c_f_Rcsv_setup_rcsv_metadata_defaults(&global_begin_block_Rcsv_parse_1__rubex_v_meta,__rubex_arg_self);

  /* Rubex file location: ext/rcsv/rcsv.rubex:84 */
  global_begin_block_Rcsv_parse_1__rubex_v_csvio = rb_funcall(rb_const_get(CLASS_OF(__rubex_arg_self), rb_intern("StringIO")), rb_intern("new"), 1 ,__rubex_arg_file_name);
  if (( csv_init(&global_begin_block_Rcsv_parse_1__rubex_v_cp,__rubex_v_csv_options) == -1 )) 
  {
    __rubex_temp_1 = rb_str_new2("Failed to initialize libcsv.");
    rb_raise(__rubex_rb_cls_RcsvParseError,"%s" ,RSTRING_PTR(rb_funcall(__rubex_temp_1, rb_intern("inspect"), 0, NULL)));
    __rubex_temp_1 = 0;

  }


  /* Rubex file location: ext/rcsv/rcsv.rubex:89 */
  __rubex_temp_1 = rb_ary_new2(0);
  global_begin_block_Rcsv_parse_1__rubex_v_meta.__rubex_v_last_entry = __rubex_temp_1;
  __rubex_temp_1 = 0;

  /* begin-rescue-else-ensure-end block begins: */

  /* Rubex file location: ext/rcsv/rcsv.rubex:120 */
  __rubex_v_begin_block_1_state = 0;
  rb_protect(__rubex_c_f_begin_block_Rcsv_parse_1, Qnil, &__rubex_v_begin_block_1_state);
  __rubex_v_begin_block_1_exec = rb_errinfo();
  __rubex_v_begin_block_1_unhandled_error = 0;
  if (0) {}
  else
  {
    /* If exception not among those captured in raise */
    if (__rubex_v_begin_block_1_state)
    {
      __rubex_v_begin_block_1_unhandled_error = 1;
    }

  }

  if (&global_begin_block_Rcsv_parse_1__rubex_v_cp) 
  {

    /* Rubex file location: ext/rcsv/rcsv.rubex:119 */
    csv_free(&global_begin_block_Rcsv_parse_1__rubex_v_cp);

  }

  if (__rubex_v_begin_block_1_unhandled_error)
  {
    rb_jump_tag(__rubex_v_begin_block_1_state);
  }

  rb_set_errinfo(Qnil);

  /* Rubex file location: ext/rcsv/rcsv.rubex:122 */
  return global_begin_block_Rcsv_parse_1__rubex_v_meta.__rubex_v_result;
}


void Init_rcsv ();
void Init_rcsv ()
{
  VALUE __rubex_rb_cls_RcsvParseError;
  VALUE __rubex_rb_cls_Rcsv;

  __rubex_rb_cls_RcsvParseError = rb_define_class("RcsvParseError", rb_eStandardError);
  __rubex_rb_cls_Rcsv = rb_define_class("Rcsv", rb_cObject);

  rb_define_singleton_method(__rubex_rb_cls_Rcsv ,"parse", __rubex_rb_f_Rcsv_parse, -1);
}

