/* C extension for c_bindings.
This file in generated by Rubex. Do not change!
*/
#include <ruby.h>
#include <stdint.h>
#include <math.h>

typedef struct exception exec;
double cos (double);
double pow (double,double);

VALUE __rubex_f_maths (int argc, VALUE* argv, VALUE __rubex_arg_self);
VALUE __rubex_f_maths (int argc, VALUE* argv, VALUE __rubex_arg_self)
{
  typedef int64_t int_64;
  typedef struct new_struct
  {
    double __rubex_v_a;
    double __rubex_v_b;
    double __rubex_v_c;
    char* __rubex_ptr_str;
  } __rubex_t_new_struct;

  double __rubex_arg_a;
  double __rubex_arg_b;
  VALUE __rubex_arg_c;
  int_64 __rubex_v_p;
  int_64 __rubex_v_rr;
  exec __rubex_v_e;
  __rubex_t_new_struct __rubex_v_s;
  if (argc != 3)
  {
    rb_raise(rb_eArgError, "Need 3 args, not %d", argc);
  }
  __rubex_arg_a=NUM2DBL(argv[0])  ;
  __rubex_arg_b=NUM2DBL(argv[1])  ;
  __rubex_arg_c=argv[2]  ;
  __rubex_v_p = (int_64)(cos(__rubex_arg_a));
  __rubex_v_rr = 332;
  __rubex_v_e.type = 3;
  __rubex_v_s.__rubex_v_a = __rubex_arg_a;
  __rubex_v_s.__rubex_v_b = __rubex_arg_b;
  if (( __rubex_v_s.__rubex_v_a > __rubex_v_s.__rubex_v_b )) 
  {
    __rubex_v_s.__rubex_ptr_str = StringValueCStr(__rubex_arg_c);

  }
  return   rb_float_new(pow(6.7,__rubex_v_s.__rubex_v_a));
}

void Init_c_bindings (void);
void Init_c_bindings (void)
{
  rb_define_method(rb_cObject ,"maths", __rubex_f_maths, -1);
}
