/* C extension for var_declarations.
This file in generated by Rubex. Do not change!
*/
#include <ruby.h>
#include <stdint.h>

VALUE __rubex_f_addition (int argc, VALUE* argv, VALUE __rubex_arg_self);
VALUE __rubex_f_addition (int argc, VALUE* argv, VALUE __rubex_arg_self)
{
  float __rubex_arg_a;
  uint64_t __rubex_arg_b;
  int32_t __rubex_arg_qq;
  float __rubex_v_c;
  int32_t __rubex_v_d;
  int32_t __rubex_v_e;
  int32_t __rubex_v_f;
  int32_t __rubex_v_tt;
  int32_t __rubex_v_u;
  char __rubex_v_q;
  int64_t __rubex_v_ww;
  int64_t __rubex_v_rew;
  VALUE __rubex_v_yy;
  if (argc != 3)
  {
    rb_raise(rb_eArgError, "Need 3 args, not %d", argc);
  }
  __rubex_arg_a=(float)NUM2DBL(argv[0])  ;
  __rubex_arg_b=(int64_t)NUM2UINT(argv[1])  ;
  __rubex_arg_qq=(int32_t)NUM2INT(argv[2])  ;
  __rubex_v_c = (float)(5.6);
  __rubex_v_f = (int32_t)(7);
  __rubex_v_tt = (int32_t)(787);
  __rubex_v_q = (char)('e');
  __rubex_v_ww = (int64_t)(-342);
  __rubex_v_rew = (int64_t)(2342);
  __rubex_v_yy = rb_str_new2("t");
  printf("%c", __rubex_v_q);
  return   rb_float_new((double)(( __rubex_arg_a + __rubex_v_c )));
}

void Init_var_declarations (void);
void Init_var_declarations (void)
{
  rb_define_method(rb_cObject ,"addition", __rubex_f_addition, -1);
}
