/* C extension for if_else.
This file in generated by Rubex. Do not change!
*/
#include <ruby.h>
#include <stdint.h>

VALUE __rubex_f_adder (int argc, VALUE* argv, VALUE __rubex_arg_self);
VALUE __rubex_f_adder (int argc, VALUE* argv, VALUE __rubex_arg_self)
{
  int __rubex_arg_a;
  int64_t __rubex_arg_b;
  double __rubex_arg_c;
  int32_t __rubex_v_d;
  if (argc != 3)
  {
    rb_raise(rb_eArgError, "Need 3 args, not %d", argc);
  }
  __rubex_arg_a=NUM2INT(argv[0])  ;
  __rubex_arg_b=(int64_t)NUM2LONG(argv[1])  ;
  __rubex_arg_c=NUM2DBL(argv[2])  ;
  if (( __rubex_arg_a < 5 )) 
  {
    __rubex_v_d = 5;

  }
  else if (( __rubex_arg_b == 44 )) 
  {
    __rubex_v_d = 44;

  }
  else if (( __rubex_arg_c >= 211 )) 
  {
    __rubex_v_d = 211;

    if (( __rubex_arg_c == 225 )) 
    {
      __rubex_v_d = 221;

    }

  }
  else
  {
    __rubex_v_d = 666;

  }
  if (! ( __rubex_v_d > 32 )) 
  {
    __rubex_v_d = -69;

  }
  if (( ( __rubex_v_d + 4 ) == 69 )) 
  {
    __rubex_v_d = 5643;

  }
  if (( ( __rubex_arg_c - 43 ) >= 321 )) 
  {
    __rubex_arg_b = -43;

  }
  return   INT2NUM(__rubex_v_d);
}

void Init_if_else (void);
void Init_if_else (void)
{
  rb_define_method(rb_cObject ,"adder", __rubex_f_adder, -1);
}
